// SPDX-License-Identifier: BUSL-1.1
import { createBearerVerifier, type BearerVerifier } from "@openshapeforge/auth";
import {
  readTrustedSessionContext,
  type SessionScope,
  type TrustedSessionContext,
} from "./trusted-context.js";

const EMPTY_SESSION: TrustedSessionContext = {
  tenantId: null,
  userId: null,
  roles: [],
  groups: [],
  scope: "self",
};

let verifierInitialized = false;
let cachedVerifier: BearerVerifier | null = null;
let cachedTenantBypassRoles: ReadonlySet<string> | null = null;

function getBearerVerifier(): BearerVerifier | null {
  if (verifierInitialized) return cachedVerifier;
  verifierInitialized = true;

  const jwksUri = process.env.OPENSHAPEFORGE_API_VERIFY_BEARER_JWKS_URI;
  const issuer = process.env.OPENSHAPEFORGE_API_VERIFY_BEARER_ISSUER;
  const audience = process.env.OPENSHAPEFORGE_API_VERIFY_BEARER_AUDIENCE;

  if (!jwksUri || !issuer) {
    cachedVerifier = null;
    return null;
  }

  if (!audience) {
    // Bearer verification is configured (JWKS + issuer) but no audience is
    // pinned, so ANY same-issuer Keycloak token — including ones minted for
    // sibling clients — would be accepted. In dev this is a loud warning; in
    // production it is fatal (see config/production-guard.ts assertProductionEnv).
    console.warn(
      "[auth] OPENSHAPEFORGE_API_VERIFY_BEARER_AUDIENCE is unset: bearer tokens are " +
        "accepted from any same-issuer client. Set it to the expected `aud` " +
        "value (e.g. erp-provider). This is fatal in production.",
    );
  }

  cachedVerifier = createBearerVerifier(
    audience ? { jwksUri, issuer, audience } : { jwksUri, issuer },
  );
  return cachedVerifier;
}

/**
 * Roles that grant tenant-wide read scope. The full set is generated by the
 * compiler from each entity's `rowScope.bypassRoles` declaration; until that
 * lands (P5/P7), an env override is supported for staged rollout:
 *
 *   APP_TENANT_BYPASS_ROLES=Platform.TenantAdmin,Case.TenantAdmin
 *
 * If the env var is unset, no role grants tenant scope and resolveScope()
 * falls through to "group"/"self".
 */
function getTenantBypassRoles(): ReadonlySet<string> {
  if (cachedTenantBypassRoles) return cachedTenantBypassRoles;
  const raw = process.env.APP_TENANT_BYPASS_ROLES ?? "";
  cachedTenantBypassRoles = new Set(
    raw
      .split(",")
      .map((role) => role.trim())
      .filter(Boolean),
  );
  return cachedTenantBypassRoles;
}

function resolveScope(roles: readonly string[], groups: readonly string[]): SessionScope {
  const bypass = getTenantBypassRoles();
  if (bypass.size > 0 && roles.some((role) => bypass.has(role))) return "tenant";
  if (groups.length > 0) return "group";
  return "self";
}

/** Test-only: reset cached state so env changes are picked up. */
export function __resetSessionResolverForTests(): void {
  verifierInitialized = false;
  cachedVerifier = null;
  cachedTenantBypassRoles = null;
}

/** Matches an `Authorization: Bearer <token>` header (case-insensitive). */
const BEARER_AUTHORIZATION = /^Bearer\s+(.+)$/i;

/**
 * Resolves the canonical session context for a request.
 *
 * - If `Authorization: Bearer …` is present, it is the caller's explicit
 *   signal to authenticate by bearer. That signal must not be
 *   downgrade-attackable, so it is resolved ONLY by the bearer verifier:
 *     - Verifier configured + token valid → use the resulting identity.
 *     - Verifier configured + verification fails → fail closed (EMPTY_SESSION).
 *     - Verifier NOT configured → fail closed (EMPTY_SESSION). We do NOT fall
 *       through to trusted-context, because doing so would silently swap the
 *       active trust boundary (a rollout/config error that leaves the bearer
 *       env unset would trust inbound HMAC-signed context headers instead of
 *       verifying the presented token — a materially larger attack surface
 *       than the operator intended, with no startup signal).
 * - If there is no bearer header, fall back to trusted-context HMAC
 *   verification. Trusted-context-only deployments are unaffected.
 *
 * The returned `groups` are raw Keycloak group paths from the access token's
 * `groups` claim. Translation to internal org-unit UUIDs (for RLS) happens
 * at the call site before `withDbSession`, against the org-unit lookup
 * table introduced in P6.
 */
export async function resolveSessionContext(
  headers: Headers,
): Promise<TrustedSessionContext> {
  const authorization = headers.get("authorization");

  if (authorization && BEARER_AUTHORIZATION.test(authorization)) {
    const verifier = getBearerVerifier();
    if (!verifier) {
      // A bearer credential was presented but no verifier is configured. Fail
      // closed rather than downgrading to the trusted-context header path.
      console.warn(
        "[auth] Authorization: Bearer header present but no bearer verifier is " +
          "configured (OPENSHAPEFORGE_API_VERIFY_BEARER_JWKS_URI/ISSUER unset). " +
          "Rejecting the request instead of falling back to trusted-context.",
      );
      return EMPTY_SESSION;
    }

    const match = BEARER_AUTHORIZATION.exec(authorization);
    const token = match![1]!;
    try {
      const { identity } = await verifier(token);
      const groups = identity.groups ?? [];
      return {
        tenantId: identity.tenantId,
        userId: identity.userId,
        roles: identity.roles,
        groups,
        scope: resolveScope(identity.roles, groups),
      };
    } catch (error) {
      console.warn(
        "[auth] Bearer verification failed:",
        error instanceof Error ? error.message : String(error),
      );
      return EMPTY_SESSION;
    }
  }

  return readTrustedSessionContext(headers);
}
