// SPDX-License-Identifier: BUSL-1.1
import {
  BearerVerifierUnavailableError,
  realmFromIssuer,
  type AuthIdentity,
} from "@openshapeforge/auth";
import type { OpenShapeForgeDatabase } from "../db/connection.js";
import { __resetBearerVerifiersForTests, getApiKeyKeyring, getBearerVerifier } from "./bearer-verifier.js";
import { looksLikeApiKey } from "./api-key/format.js";
// ---- identity ↔ Relation link (auth/identity-link.ts) ----
import {
  NotInvitedError,
  identityClaimsFromToken,
  resolveIdentityLink,
  withSessionRelation,
  type IdentityClaims,
  type IdentityLinkState,
} from "./identity-link.js";
// ---- end identity ↔ Relation link ----
import { resolveApiKeySession } from "./api-key/resolve.js";
import { loginSessionBindingFromClaims } from "./login-session-binding.js";
import {
  __resetOrganizationAddressForTests,
  assertSessionAddressesOrganization,
  OrganizationAddressError,
} from "./organization-address.js";
import { configuredOrganizationServiceAccount } from "./organization-service-identities.js";
import { personSessionRoles } from "./person-roles.js";
import { SessionAuthenticationUnavailableError } from "./session-unavailable.js";
import { resolveRelationGroupMembershipIds } from "./relation-group-memberships.js";
import {
  OrganizationBindingError,
  sameTenantId,
  type OrganizationResourceBinding,
} from "./organization-binding.js";
import {
  __resetTenantResolutionForTests,
  resolveHostOrganizationTenant,
  resolveScopedServiceTenant,
  resolveTenantForBoundOrganization,
  resolveTenantFromOrganization,
} from "./tenant-resolution.js";
import {
  readTrustedSessionContext,
  type SessionScope,
  type TrustedSessionContext,
} from "./trusted-context.js";

export type ResolveSessionOptions = {
  /**
   * Required for API keys and organization-to-tenant registry resolution.
   * Host organization mode refuses sessions without registry proof.
   */
  db?: OpenShapeForgeDatabase | undefined;
  /**
   * Preserve authentication-service unavailability as a distinct failure.
   * Ordinary callers keep the historical anonymous-session fallback.
   */
  failOnUnavailable?: boolean;
  /** Exact resource audience required in addition to the configured verifier audience.
   * Supplying this makes the endpoint bearer-only (no API key or trusted context).
   */
  requiredAudience?: string;
  /**
   * Set by the per-organization MCP resource (`/<alias>`).
   * The session is then only produced from a bearer JWT that is bound to that
   * resource — membership of the organization, the resource URL in `aud`, a
   * tenant linked to the organization — and is pinned to that tenant. Any
   * other credential is refused, and a bound token that fails a check raises
   * {@link OrganizationBindingError} instead of degrading to the empty session
   * (see auth/organization-binding.ts).
   */
  organization?: OrganizationResourceBinding;
};

/** Read per request: hosts and standalone processes may configure this after import. */
function hostOrganizationContext(): boolean {
  return process.env.OPENSHAPEFORGE_ORGANIZATION_CONTEXT === "host";
}

function bearerVerifierUnavailable(error: unknown): boolean {
  return error instanceof BearerVerifierUnavailableError;
}

const EMPTY_SESSION: TrustedSessionContext = {
  tenantId: null,
  userId: null,
  roles: [],
  groups: [],
  relationGroupIds: [],
  scope: "self",
  credential: "none",
};

let cachedTenantBypassRoles: ReadonlySet<string> | null = null;

/**
 * Roles that grant tenant-wide read scope. The full set is generated by the
 * compiler from each entity's `rowScope.bypassRoles` declaration; until that
 * lands (P5/P7), an env override is supported for staged rollout:
 *
 *   APP_TENANT_BYPASS_ROLES=Platform.TenantAdmin,Case.TenantAdmin
 *
 * If the env var is unset, no role grants tenant scope and resolveScope()
 * falls through to "group"/"self".
 */
function getTenantBypassRoles(): ReadonlySet<string> {
  if (cachedTenantBypassRoles) return cachedTenantBypassRoles;
  const raw = process.env.APP_TENANT_BYPASS_ROLES ?? "";
  cachedTenantBypassRoles = new Set(
    raw
      .split(",")
      .map((role) => role.trim())
      .filter(Boolean),
  );
  return cachedTenantBypassRoles;
}

function resolveScope(roles: readonly string[], groups: readonly string[]): SessionScope {
  const bypass = getTenantBypassRoles();
  if (bypass.size > 0 && roles.some((role) => bypass.has(role))) return "tenant";
  if (groups.length > 0) return "group";
  return "self";
}

/** Test-only: reset cached state so env changes are picked up. */
export function __resetSessionResolverForTests(): void {
  cachedTenantBypassRoles = null;
  identityLinkOverride = null;
  __resetBearerVerifiersForTests();
  __resetTenantResolutionForTests();
  __resetOrganizationAddressForTests();
}

const BEARER_AUTHORIZATION = /^Bearer\s+(.+)$/i;

/**
 * Test-only: stand in for the membership read (`resolveIdentityLink`) so the
 * bearer paths can be exercised end to end without a database. A person is
 * still refused without one in production; this seam is the only way past
 * that. Cleared by `__resetSessionResolverForTests`.
 */
export type IdentityLinkForTests = (
  session: { tenantId: string; userId: string },
  claims: IdentityClaims,
) => Promise<IdentityLinkState | null>;
export function __setIdentityLinkForTests(resolver: IdentityLinkForTests | null): void {
  identityLinkOverride = resolver;
}
let identityLinkOverride: IdentityLinkForTests | null = null;

/**
 * Verify a Keycloak token through the ordinary bearer path and flatten it to
 * the fields the API key resolver needs. Shared with the interactive path on
 * purpose: there is exactly one place where a token becomes an identity.
 */
async function verifyBearerIdentity(
  token: string,
  credential: { tenantId: string; keycloakClientId: string },
  db: OpenShapeForgeDatabase,
) {
  const verifier = getBearerVerifier();
  if (!verifier) {
    throw new Error("Bearer verifier is not configured.");
  }
  const { identity, claims } = await verifier(token);
  const tenantId = hostOrganizationContext()
    ? await resolveScopedServiceTenant(identity, claims, {
        tenantId: credential.tenantId, clientId: credential.keycloakClientId,
      }, db)
    : identity.tenantId;
  return {
    tenantId,
    userId: identity.userId,
    roles: sessionIdentityRoles(identity),
    groups: identity.groups ?? [],
    scopes: identity.scopes ?? [],
  };
}

/**
 * Effective roles for a SERVICE identity outside host organization context = realm roles ∪ every
 * `resource_access` client's roles. Keycloak expands realm and client
 * composites into per-client roles under `resource_access`, so entity roles
 * like `Relations.All.ReadWrite` only exist there — realm_access alone would
 * deny every generated-entity operation once role enforcement runs. Merging
 * all clients is safe because the entity guard matches exact strings from
 * the manifest, so unrelated built-ins (`account.manage-account`, …) are
 * inert. Exported for unit testing.
 *
 * Never applied to a PERSON: see {@link personSessionRoles}.
 */
export function mergeIdentityRoles(identity: {
  roles: readonly string[];
  clientRoles?: Record<string, string[]> | undefined;
}): string[] {
  return [
    ...new Set([
      ...identity.roles,
      ...Object.values(identity.clientRoles ?? {}).flat(),
    ]),
  ].sort();
}

/** Keycloak's own naming of a client-credentials principal, on verified claims. */
function isServiceAccountToken(claims: Record<string, unknown>): boolean {
  return typeof claims.azp === "string" && claims.azp.length > 0 &&
    claims.preferred_username === `service-account-${claims.azp}`;
}

/** Service identities (configured service accounts, API-key exchanges). */
function sessionIdentityRoles(identity: AuthIdentity): string[] {
  if (!hostOrganizationContext()) return mergeIdentityRoles(identity);
  // Client roles belong to a resource server, not every sibling client in the
  // realm. Organization-local claims stay nested; ambiguous tokens are refused
  // before these roles can become an authenticated session. Realm roles remain
  // issuer-wide grants and must not contain flattened per-organization rights.
  const audience = process.env.OPENSHAPEFORGE_API_VERIFY_BEARER_AUDIENCE;
  const clientRoles = audience ? identity.clientRoles?.[audience] : undefined;
  return [...new Set([...identity.roles, ...(clientRoles ?? [])])].sort();
}

/**
 * Resolves the canonical session context for a request, and refuses it when
 * the request's short address names another organization than the
 * credential's (see {@link assertSessionAddressesOrganization}).
 */
export async function resolveSessionContext(
  headers: Headers,
  options: ResolveSessionOptions = {},
): Promise<TrustedSessionContext> {
  const session = await withSessionRelation(await resolveCredentialSession(headers, options), options);
  return assertSessionAddressesOrganization(
    headers,
    session,
    { db: options.db, bound: options.organization !== undefined },
    EMPTY_SESSION,
  );
}

/**
 * Resolves the session a credential proves.
 *
 * - If `Authorization: Bearer …` carries an `osf_`-prefixed API key, it is
 *   resolved ONLY by the API key path (see api-key/resolve.ts). A key is
 *   ultimately verified as a Keycloak token by the same verifier below, so it
 *   introduces no second source of roles; what it adds is a credential that can
 *   be handed to an external party and revoked without touching the realm.
 *   Like the bearer path, it never falls through on failure.
 * - Otherwise, if `Authorization: Bearer …` is present, it is the caller's
 *   explicit signal to authenticate by bearer. That signal must not be
 *   downgrade-attackable, so it is resolved ONLY by the bearer verifier:
 *     - Verifier configured + token valid → use the resulting identity.
 *     - Verifier configured + verification fails → fail closed (EMPTY_SESSION).
 *     - Verifier NOT configured → fail closed (EMPTY_SESSION). We do NOT fall
 *       through to trusted-context, because doing so would silently swap the
 *       active trust boundary (a rollout/config error that leaves the bearer
 *       env unset would trust inbound HMAC-signed context headers instead of
 *       verifying the presented token — a materially larger attack surface
 *       than the operator intended, with no startup signal).
 * - Without a bearer header, trusted-context HMAC verification remains
 *   available only outside host mode and bearer-only resources.
 *
 * The returned `groups` are raw Keycloak group paths from the access token's
 * `groups` claim. Translation to internal org-unit UUIDs (for RLS) happens
 * at the call site before `withDbSession`, against the org-unit lookup
 * table introduced in P6.
 */
async function resolveCredentialSession(
  headers: Headers,
  options: ResolveSessionOptions = {},
): Promise<TrustedSessionContext> {
  const authorization = headers.get("authorization");

  if (authorization && BEARER_AUTHORIZATION.test(authorization)) {
    const presented = BEARER_AUTHORIZATION.exec(authorization)![1]!;

    // An API key is routed by its prefix BEFORE the JWKS path, and once routed
    // it never falls through: a credential shaped like ours is ours to accept
    // or reject. Falling through would let a caller who knows the prefix probe
    // the JWKS verifier with arbitrary strings, and — worse — a deployment that
    // forgot to configure the keyring would silently start treating API keys as
    // JWTs, which is the same downgrade the bearer path already refuses.
    if (looksLikeApiKey(presented)) {
      if (options.organization || options.requiredAudience !== undefined) {
        // An API key proves a tenant, not an Organization membership, and
        // carries no per-resource audience. Fail closed on the bound resource.
        console.warn(
          "[auth] An API key was presented to a bearer-only resource. Rejecting.",
        );
        return EMPTY_SESSION;
      }
      const keyring = getApiKeyKeyring();
      const issuer = process.env.OPENSHAPEFORGE_API_VERIFY_BEARER_ISSUER;

      if (!options.db || !keyring || !issuer || !getBearerVerifier()) {
        console.warn(
          "[auth] An API key was presented but the key path is not fully configured " +
            "(needs a database, OPENSHAPEFORGE_API_KEY_SECRET_KEYS, and a complete " +
            "bearer verifier). Rejecting.",
        );
        if (options.failOnUnavailable) {
          throw new SessionAuthenticationUnavailableError();
        }
        return EMPTY_SESSION;
      }

      const session = await resolveApiKeySession(
        {
          db: options.db,
          keyring,
          issuer,
          verifyToken: (token, credential) => verifyBearerIdentity(token, credential, options.db!),
          resolveScope,
        },
        presented,
      );
      return session ?? EMPTY_SESSION;
    }

    const verifier = getBearerVerifier(
      hostOrganizationContext() && options.requiredAudience !== undefined,
      options.organization !== undefined,
    );
    if (!verifier) {
      // A bearer credential was presented but no verifier is configured. Fail
      // closed rather than downgrading to the trusted-context header path.
      console.warn(
        "[auth] Authorization: Bearer header present but no bearer verifier is " +
          "configured (OPENSHAPEFORGE_API_VERIFY_BEARER_JWKS_URI/ISSUER unset). " +
          "Rejecting the request instead of falling back to trusted-context.",
      );
      if (options.failOnUnavailable) {
        throw new SessionAuthenticationUnavailableError();
      }
      return EMPTY_SESSION;
    }

    const match = BEARER_AUTHORIZATION.exec(authorization);
    const token = match![1]!;
    try {
      const { identity, claims } = await verifier(token);
      if (options.organization &&
          (typeof claims.azp !== "string" || !claims.azp.trim())) return EMPTY_SESSION;
      if (hostOrganizationContext() && options.requiredAudience !== undefined &&
          (typeof claims.azp !== "string" || !claims.azp.trim())) return EMPTY_SESSION;
      if (options.requiredAudience !== undefined &&
          !(typeof claims.aud === "string" ? [claims.aud] : claims.aud ?? [])
            .includes(options.requiredAudience)) return EMPTY_SESSION;
      const groups = identity.groups ?? [];
      const hostMode = hostOrganizationContext();
      const configuredService = hostMode
        ? configuredOrganizationServiceAccount(claims, identity.tenantId)
        : undefined;
      const hostTenantId = hostMode
        ? configuredService
          ? await resolveScopedServiceTenant(identity, claims, configuredService, options.db)
          : await resolveHostOrganizationTenant(identity, claims, options.db)
        : null;
      if (hostMode && (!hostTenantId || !identity.userId)) return EMPTY_SESSION;
      // On a per-organization resource the tenant is the one the path's
      // organization links to, and nothing else in the token may pick it.
      // Shared host endpoints use the verified selected organization. The shared
      // mount retains tid preference followed by organization resolution.
      const tenantId = options.organization
        ? await resolveTenantForBoundOrganization(
            identity,
            claims as Record<string, unknown>,
            options.organization,
            options.db,
          )
        : hostMode ? hostTenantId : identity.tenantId ??
          (await resolveTenantFromOrganization(
            identity,
            claims as Record<string, unknown>,
            options.db,
          ));
      if (hostMode && !sameTenantId(tenantId, hostTenantId)) return EMPTY_SESSION;
      // ---- identity ↔ Relation link (auth/identity-link.ts) ----
      // A person's first session in a tenant links (or records) the Relation
      // they act as; later sessions read it back. The same row carries the
      // person's roles in that tenant.
      const personClaims = identityClaimsFromToken(claims as Record<string, unknown>);
      // A client-credentials token is not a person: an explicitly configured
      // service identity, or any service account the verifier already
      // accepted (Keycloak names them `service-account-<clientId>` and the
      // authorized party is that client — both are VERIFIED claims here, not
      // unverified input). Persons take their roles from the membership row;
      // service identities keep their client roles.
      const serviceAccount = configuredOrganizationServiceAccount(claims as Record<string, unknown>, tenantId);
      const isPerson = !serviceAccount && !isServiceAccountToken(claims) && personClaims !== null;
      // A person whose membership cannot be resolved has no session: the row
      // is where admission and roles live, so without a database there is
      // nothing to decide with (503), and without a tenant or subject there
      // is nobody to decide for (no session). Never a token-only person.
      if (isPerson && !options.db && !identityLinkOverride) {
        throw new SessionAuthenticationUnavailableError(
          "This surface resolves sessions without a database; a person cannot be admitted here.",
        );
      }
      if (isPerson && (!tenantId || !identity.userId)) return EMPTY_SESSION;
      // The link is read on a session that holds no organization roles yet:
      // the row itself is the source of those, and RLS on it fences by tenant
      // and by the identity being one's own.
      const linkSession = { roles: [...identity.roles], groups, scope: resolveScope(identity.roles, groups) };
      const relation =
        isPerson && tenantId && identity.userId
          ? identityLinkOverride
            ? await identityLinkOverride({ tenantId, userId: identity.userId }, personClaims)
            : await resolveIdentityLink(
                options.db!,
                { tenantId, userId: identity.userId, ...linkSession },
                personClaims,
              )
          : null;
      if (isPerson && !relation) {
        throw new SessionAuthenticationUnavailableError(
          "The membership record could not be resolved; try again.",
        );
      }
      const effectiveRoles = isPerson && relation
        ? personSessionRoles(identity, relation, realmFromIssuer(claims.iss))
        : sessionIdentityRoles(identity);
      const effectiveScope = resolveScope(effectiveRoles, groups);
      const loginSessionBinding = loginSessionBindingFromClaims(
        claims as Record<string, unknown>,
      );
      const relationGroupIds =
        tenantId && identity.userId && options.db && !serviceAccount && personClaims
          ? await resolveRelationGroupMembershipIds(
              options.db,
              {
                tenantId,
                userId: identity.userId,
                roles: effectiveRoles,
                groups,
                scope: effectiveScope,
              },
              { issuer: personClaims.issuer, subject: personClaims.subject },
            )
          : [];
      // ---- end identity ↔ Relation link ----
      return {
        tenantId,
        userId: identity.userId,
        ...(typeof claims.iss === "string" ? { issuer: claims.iss } : {}),
        ...(loginSessionBinding ? { loginSessionBinding } : {}),
        userDisplayName: relation?.displayName ?? null,
        ...(typeof claims.locale === "string" && claims.locale.trim() ? { locale: claims.locale.trim() } : {}),
        roles: effectiveRoles,
        oauthScopes: identity.scopes ?? [],
        groups,
        relationGroupIds,
        scope: effectiveScope,
        credential: "bearer",
        relation,
      };
    } catch (error) {
      if (error instanceof NotInvitedError) {
        // The token verified and names a real person; this organization has
        // simply never been told to expect them. Answering EMPTY_SESSION here
        // would authenticate them into a tenant nobody admitted them to, which
        // is the hole this closes, and a bare 401 would tell them nothing they
        // could act on. Let it through as the 403 it is — the message names
        // the way in.
        console.warn(`[auth] ${error.message}`);
        throw error;
      }
      if (error instanceof SessionAuthenticationUnavailableError) {
        // The token verified; the record that says whether this tenant
        // admitted the person and which roles they hold here could not be
        // read. Not an anonymous session and not a token-only one: 503.
        console.warn(`[auth] ${error.message}`);
        throw error;
      }
      if (error instanceof OrganizationBindingError) {
        // The token verified; it is just not a token for this resource. The
        // caller answers with the scopes to request rather than a bare 401,
        // and the log keeps the reason the caller must not learn.
        console.warn(
          `[auth] Bearer token refused on organization resource ${options.organization?.resource}: ${error.reason}.`,
        );
        throw error;
      }
      console.warn(
        "[auth] Bearer verification failed:",
        error instanceof Error ? error.message : String(error),
      );
      if (options.failOnUnavailable && bearerVerifierUnavailable(error)) {
        throw new SessionAuthenticationUnavailableError();
      }
      return EMPTY_SESSION;
    }
  }

  if (options.organization || options.requiredAudience !== undefined || hostOrganizationContext()) {
    // Trusted-context headers name a tenant directly; they cannot prove
    // selected membership or resource audience. Strict endpoints refuse them.
    return EMPTY_SESSION;
  }

  return readTrustedSessionContext(headers);
}
