// SPDX-License-Identifier: BUSL-1.1
/**
 * The facts every credential path shares and none owns: the empty session,
 * the host-organization flag and the row scope a role set implies. A leaf so
 * that session-resolver.ts (the dispatcher) and bearer-session.ts (the bearer
 * branch) both import it and neither imports the other.
 */
import type { SessionScope, TrustedSessionContext } from "./trusted-context.js";

/** Read per request: hosts and standalone processes may configure this after import. */
export function hostOrganizationContext(): boolean {
  return process.env.OPENSHAPEFORGE_ORGANIZATION_CONTEXT === "host";
}

export const EMPTY_SESSION: TrustedSessionContext = {
  tenantId: null,
  userId: null,
  roles: [],
  groups: [],
  relationGroupIds: [],
  scope: "self",
  credential: "none",
};

let cachedTenantBypassRoles: ReadonlySet<string> | null = null;

/**
 * Roles that grant tenant-wide read scope. The full set is generated by the
 * compiler from each entity's `rowScope.bypassRoles` declaration; until that
 * lands (P5/P7), an env override is supported for staged rollout:
 *
 *   APP_TENANT_BYPASS_ROLES=Platform.TenantAdmin,Case.TenantAdmin
 *
 * If the env var is unset, no role grants tenant scope and resolveScope()
 * falls through to "group"/"self".
 */
function getTenantBypassRoles(): ReadonlySet<string> {
  if (cachedTenantBypassRoles) return cachedTenantBypassRoles;
  const raw = process.env.APP_TENANT_BYPASS_ROLES ?? "";
  cachedTenantBypassRoles = new Set(
    raw
      .split(",")
      .map((role) => role.trim())
      .filter(Boolean),
  );
  return cachedTenantBypassRoles;
}

export function resolveScope(roles: readonly string[], groups: readonly string[]): SessionScope {
  const bypass = getTenantBypassRoles();
  if (bypass.size > 0 && roles.some((role) => bypass.has(role))) return "tenant";
  if (groups.length > 0) return "group";
  return "self";
}

/** Test-only: forget the parsed bypass roles so env changes are picked up. */
export function __resetSessionScopeForTests(): void {
  cachedTenantBypassRoles = null;
}
