// SPDX-License-Identifier: BUSL-1.1
/**
 * Resolves the session a credential proves: an API key, a bearer token, or
 * a signed trusted-context bundle — each by its own path, never one falling
 * through to another. `identity.ts` composes this with the acting Relation
 * and the organization address check into `resolveSessionContext`.
 */
import { BearerVerifierUnavailableError } from "@openshapeforge/auth";
import type { OpenShapeForgeDatabase } from "../db/connection.js";
import { __resetBearerVerifiersForTests, getApiKeyKeyring, getBearerVerifier } from "./bearer-verifier.js";
import { looksLikeApiKey } from "./api-key/format.js";
import { __resetBearerSessionForTests, resolveVerifiedBearerSession, sessionIdentityRoles } from "./bearer-session.js";
// ---- identity ↔ Relation link (auth/identity-link.ts) ----
import { NotInvitedError } from "./identity-link.js";
// ---- end identity ↔ Relation link ----
import { resolveApiKeySession } from "./api-key/resolve.js";
import { __resetOrganizationAddressForTests } from "./organization-address.js";
import { SessionAuthenticationUnavailableError } from "./session-unavailable.js";
import {
  OrganizationBindingError,
  type OrganizationResourceBinding,
} from "./organization-binding.js";
import {
  __resetTenantResolutionForTests,
  resolveScopedServiceTenant,
} from "./tenant-resolution.js";
import {
  readTrustedSessionContext,
  type SessionScope,
  type TrustedSessionContext,
} from "./trusted-context.js";

export type ResolveSessionOptions = {
  /**
   * Required for API keys and organization-to-tenant registry resolution.
   * Host organization mode refuses sessions without registry proof.
   */
  db?: OpenShapeForgeDatabase | undefined;
  /** Exact resource audience required in addition to the configured verifier audience.
   * Supplying this makes the endpoint bearer-only (no API key or trusted context).
   */
  requiredAudience?: string;
  /**
   * Set by the per-organization MCP resource (`/<alias>`).
   * The session is then only produced from a bearer JWT that is bound to that
   * resource — membership of the organization, the resource URL in `aud`, a
   * tenant linked to the organization — and is pinned to that tenant. Any
   * other credential is refused, and a bound token that fails a check raises
   * {@link OrganizationBindingError} instead of degrading to the empty session
   * (see auth/organization-binding.ts).
   */
  organization?: OrganizationResourceBinding;
};

/** Read per request: hosts and standalone processes may configure this after import. */
export function hostOrganizationContext(): boolean {
  return process.env.OPENSHAPEFORGE_ORGANIZATION_CONTEXT === "host";
}

function bearerVerifierUnavailable(error: unknown): boolean {
  return error instanceof BearerVerifierUnavailableError;
}

export const EMPTY_SESSION: TrustedSessionContext = {
  tenantId: null,
  userId: null,
  roles: [],
  groups: [],
  relationGroupIds: [],
  scope: "self",
  credential: "none",
};

let cachedTenantBypassRoles: ReadonlySet<string> | null = null;

/**
 * Roles that grant tenant-wide read scope. The full set is generated by the
 * compiler from each entity's `rowScope.bypassRoles` declaration; until that
 * lands (P5/P7), an env override is supported for staged rollout:
 *
 *   APP_TENANT_BYPASS_ROLES=Platform.TenantAdmin,Case.TenantAdmin
 *
 * If the env var is unset, no role grants tenant scope and resolveScope()
 * falls through to "group"/"self".
 */
function getTenantBypassRoles(): ReadonlySet<string> {
  if (cachedTenantBypassRoles) return cachedTenantBypassRoles;
  const raw = process.env.APP_TENANT_BYPASS_ROLES ?? "";
  cachedTenantBypassRoles = new Set(
    raw
      .split(",")
      .map((role) => role.trim())
      .filter(Boolean),
  );
  return cachedTenantBypassRoles;
}

export function resolveScope(roles: readonly string[], groups: readonly string[]): SessionScope {
  const bypass = getTenantBypassRoles();
  if (bypass.size > 0 && roles.some((role) => bypass.has(role))) return "tenant";
  if (groups.length > 0) return "group";
  return "self";
}

/** Test-only: reset cached state so env changes are picked up. */
export function __resetSessionResolverForTests(): void {
  __resetBearerSessionForTests();
  cachedTenantBypassRoles = null;
  __resetBearerVerifiersForTests();
  __resetTenantResolutionForTests();
  __resetOrganizationAddressForTests();
}

const BEARER_AUTHORIZATION = /^Bearer\s+(.+)$/i;

/**
 * Verify a Keycloak token through the ordinary bearer path and flatten it to
 * the fields the API key resolver needs. Shared with the interactive path on
 * purpose: there is exactly one place where a token becomes an identity.
 */
async function verifyBearerIdentity(
  token: string,
  credential: { tenantId: string; keycloakClientId: string },
  db: OpenShapeForgeDatabase,
) {
  const verifier = getBearerVerifier();
  if (!verifier) {
    throw new Error("Bearer verifier is not configured.");
  }
  const { identity, claims } = await verifier(token);
  const tenantId = hostOrganizationContext()
    ? await resolveScopedServiceTenant(identity, claims, {
        tenantId: credential.tenantId, clientId: credential.keycloakClientId,
      }, db)
    : identity.tenantId;
  return {
    tenantId,
    userId: identity.userId,
    roles: sessionIdentityRoles(identity),
    groups: identity.groups ?? [],
    scopes: identity.scopes ?? [],
  };
}

/**
 * Resolves the session a credential proves.
 *
 * - If `Authorization: Bearer …` carries an `osf_`-prefixed API key, it is
 *   resolved ONLY by the API key path (see api-key/resolve.ts). A key is
 *   ultimately verified as a Keycloak token by the same verifier below, so it
 *   introduces no second source of roles; what it adds is a credential that can
 *   be handed to an external party and revoked without touching the realm.
 *   Like the bearer path, it never falls through on failure.
 * - Otherwise, if `Authorization: Bearer …` is present, it is the caller's
 *   explicit signal to authenticate by bearer. That signal must not be
 *   downgrade-attackable, so it is resolved ONLY by the bearer verifier:
 *     - Verifier configured + token valid → use the resulting identity.
 *     - Verifier configured + token refused → fail closed (EMPTY_SESSION).
 *     - Verifier configured but unreachable (JWKS outage) → 503
 *       AUTHENTICATION_UNAVAILABLE: the deployment cannot decide, so it says
 *       so instead of answering as nobody.
 *     - Verifier NOT configured → 503 AUTHENTICATION_UNAVAILABLE as well. We
 *       do NOT fall through to trusted-context, because doing so would swap the
 *       active trust boundary (a rollout/config error that leaves the bearer
 *       env unset would trust inbound HMAC-signed context headers instead of
 *       verifying the presented token — a materially larger attack surface
 *       than the operator intended, with no startup signal).
 * - Without a bearer header, trusted-context HMAC verification remains
 *   available only outside host mode and bearer-only resources.
 *
 * The returned `groups` are raw Keycloak group paths from the access token's
 * `groups` claim. Translation to internal org-unit UUIDs (for RLS) happens
 * at the call site before `withDbSession`, against the org-unit lookup
 * table introduced in P6.
 */
export async function resolveCredentialSession(
  headers: Headers,
  options: ResolveSessionOptions = {},
): Promise<TrustedSessionContext> {
  const authorization = headers.get("authorization");

  if (authorization && BEARER_AUTHORIZATION.test(authorization)) {
    const presented = BEARER_AUTHORIZATION.exec(authorization)![1]!;

    // An API key is routed by its prefix BEFORE the JWKS path, and once routed
    // it never falls through: a credential shaped like ours is ours to accept
    // or reject. Falling through would let a caller who knows the prefix probe
    // the JWKS verifier with arbitrary strings, and — worse — a deployment that
    // forgot to configure the keyring would silently start treating API keys as
    // JWTs, which is the same downgrade the bearer path already refuses.
    if (looksLikeApiKey(presented)) {
      if (options.organization || options.requiredAudience !== undefined) {
        // An API key proves a tenant, not an Organization membership, and
        // carries no per-resource audience. Fail closed on the bound resource.
        console.warn(
          "[auth] An API key was presented to a bearer-only resource. Rejecting.",
        );
        return EMPTY_SESSION;
      }
      const keyring = getApiKeyKeyring();
      const issuer = process.env.OPENSHAPEFORGE_API_VERIFY_BEARER_ISSUER;

      if (!options.db || !keyring || !issuer || !getBearerVerifier()) {
        console.warn(
          "[auth] An API key was presented but the key path is not fully configured " +
            "(needs a database, OPENSHAPEFORGE_API_KEY_SECRET_KEYS, and a complete " +
            "bearer verifier). Rejecting.",
        );
        throw new SessionAuthenticationUnavailableError(
          "API keys cannot be verified: the key path needs a database, OPENSHAPEFORGE_API_KEY_SECRET_KEYS and a complete bearer verifier.",
        );
      }

      const session = await resolveApiKeySession(
        {
          db: options.db,
          keyring,
          issuer,
          verifyToken: (token, credential) => verifyBearerIdentity(token, credential, options.db!),
          resolveScope,
        },
        presented,
      );
      return session ?? EMPTY_SESSION;
    }

    const verifier = getBearerVerifier(
      hostOrganizationContext() && options.requiredAudience !== undefined,
      options.organization !== undefined,
    );
    if (!verifier) {
      // A bearer credential was presented but no verifier is configured. That
      // is a deployment that cannot say who this is — not an anonymous caller,
      // and never a downgrade to the trusted-context header path (the bearer
      // signal must not be downgrade-attackable). 503, so a signed-in browser
      // whose host forwards its token sees the outage instead of running as
      // nobody.
      console.warn(
        "[auth] Authorization: Bearer header present but no bearer verifier is " +
          "configured (OPENSHAPEFORGE_API_VERIFY_BEARER_JWKS_URI/ISSUER unset). " +
          "Refusing the request as unavailable.",
      );
      throw new SessionAuthenticationUnavailableError(
        "Bearer tokens cannot be verified: OPENSHAPEFORGE_API_VERIFY_BEARER_JWKS_URI and _ISSUER are not configured.",
      );
    }

    const match = BEARER_AUTHORIZATION.exec(authorization);
    const token = match![1]!;
    try {
      return await resolveVerifiedBearerSession(verifier, token, options);
    } catch (error) {
      if (error instanceof NotInvitedError) {
        // The token verified and names a real person; this organization has
        // simply never been told to expect them. Answering EMPTY_SESSION here
        // would authenticate them into a tenant nobody admitted them to, which
        // is the hole this closes, and a bare 401 would tell them nothing they
        // could act on. Let it through as the 403 it is — the message names
        // the way in.
        console.warn(`[auth] ${error.message}`);
        throw error;
      }
      if (error instanceof SessionAuthenticationUnavailableError) {
        // The token verified; the record that says whether this tenant
        // admitted the person and which roles they hold here could not be
        // read. Not an anonymous session and not a token-only one: 503.
        console.warn(`[auth] ${error.message}`);
        throw error;
      }
      if (error instanceof OrganizationBindingError) {
        // The token verified; it is just not a token for this resource. The
        // caller answers with the scopes to request rather than a bare 401,
        // and the log keeps the reason the caller must not learn.
        console.warn(
          `[auth] Bearer token refused on organization resource ${options.organization?.resource}: ${error.reason}.`,
        );
        throw error;
      }
      console.warn(
        "[auth] Bearer verification failed:",
        error instanceof Error ? error.message : String(error),
      );
      // An outage of the verifier (JWKS unreachable, unusable key material)
      // is not a refusal of this token: 503, never an anonymous session.
      if (bearerVerifierUnavailable(error)) {
        throw new SessionAuthenticationUnavailableError(
          "Bearer tokens cannot be verified: the remote bearer verifier is unavailable.",
        );
      }
      return EMPTY_SESSION;
    }
  }

  if (options.organization || options.requiredAudience !== undefined || hostOrganizationContext()) {
    // Trusted-context headers name a tenant directly; they cannot prove
    // selected membership or resource audience. Strict endpoints refuse them.
    return EMPTY_SESSION;
  }

  return readTrustedSessionContext(headers);
}

