// SPDX-License-Identifier: BUSL-1.1
/**
 * Which tenant a verified bearer token is for — the registry side of session
 * resolution (see ./identity.ts for the resolver that calls this).
 */
import {
  ORGANIZATION_TENANT_CACHE_TTL_MS,
  organizationTenantCacheKey,
  realmFromIssuer,
  selectOrganizationMembership,
  type AuthIdentity,
} from "@openshapeforge/auth";
import { sql } from "kysely";
import type { OpenShapeForgeDatabase } from "../db/connection.js";
import { withDbSession } from "../db/session.js";
import {
  bindOrganizationResource,
  OrganizationBindingError,
  sameTenantId,
  type OrganizationResourceBinding,
  type TenantForOrganization,
} from "./organization-binding.js";

/**
 * Test-only: stand in for the registry read
 * (`app.tenant_for_keycloak_organization`) so the organization paths can be
 * exercised end to end without a database. Cleared by the reset above.
 */
export function __setTenantForOrganizationForTests(
  lookup: TenantForOrganization | null,
): void {
  tenantForOrganizationOverride = lookup;
}
let tenantForOrganizationOverride: TenantForOrganization | null = null;

/** Test-only. */
export function __resetTenantResolutionForTests(): void {
  organizationTenantCache.clear();
  tenantForOrganizationOverride = null;
}

// ---------------------------------------------------------------------------
// Tenant from Keycloak Organization membership
//
// A token names its tenant in one of two ways:
//
//   - `tid`: a user attribute the dev realm maps straight into the token. It is
//     the legacy shape and stays authoritative only outside host mode.
//   - `organization.<alias>.id`: Keycloak's own Organization Membership mapper
//     (client scope `organization`, "add organization id" on). This is how a
//     deployment that models tenants as Keycloak Organizations — the shape the
//     control plane provisions — says which tenant the user is in. The
//     Organization id is NOT the tenant id (the two are generated by different
//     systems and are never interchangeable); the link is the registry row
//     `platform.tenants.keycloak_organization_id`, stamped by provisioning.
//
// So an organization-only token needs one registry read, and it needs it
// before the session has a tenant to scope that read by. That is exactly what
// `app.tenant_for_keycloak_organization(realm, organization_id)` exists for
// (db/migrations/app-helpers.ts): a point lookup with a function-scoped RLS
// bypass, answering one id for one (realm, organization) pair the caller has
// already proved membership of through a signed token.
//
// Fail-closed throughout: no database, no membership with an id, a membership
// no registry row links to, or an ambiguous set of memberships all leave the
// tenant null, which every surface already rejects as unauthenticated. The
// realm is taken from `iss` and matched against `tenants.keycloak_realm`, so a
// row provisioned for one realm can never be reached by a token from another.

// The TTL, the realm parser, the membership selection and the cache key live in
// `@openshapeforge/auth` (organization-tenant.ts) because Hubble's separately
// bundled plugin runtime needs exactly the same answers and cannot import this
// file. The cache instance below is process state and stays here.
const organizationTenantCache = new Map<string, { tenantId: string; expiresAtMs: number }>();

// Re-exported so this module keeps being the one address the rest of apps/api
// (and its tests) use for the organization path; the implementations are in
// `@openshapeforge/auth`.
export { organizationTenantCacheKey, realmFromIssuer, selectOrganizationMembership };

/**
 * The registry read behind both organization paths: which tenant is linked to
 * (realm, organization id). Cached briefly; null when no row links them.
 */
export async function lookupTenantForOrganization(
  db: OpenShapeForgeDatabase | undefined,
  realm: string,
  organizationId: string,
): Promise<string | null> {
  if (tenantForOrganizationOverride) {
    return tenantForOrganizationOverride(realm, organizationId);
  }
  if (!db) return null;
  const cacheKey = organizationTenantCacheKey(realm, organizationId);
  const cached = organizationTenantCache.get(cacheKey);
  if (cached && cached.expiresAtMs > Date.now()) return cached.tenantId;

  const result = await sql<{ tenant_id: string | null }>`
    select app.tenant_for_keycloak_organization(${realm}, ${organizationId}) as tenant_id
  `.execute(db);
  const tenantId = result.rows[0]?.tenant_id ?? null;
  if (tenantId) {
    organizationTenantCache.set(cacheKey, {
      tenantId,
      expiresAtMs: Date.now() + ORGANIZATION_TENANT_CACHE_TTL_MS,
    });
  }
  return tenantId;
}

export async function resolveTenantFromOrganization(
  identity: AuthIdentity,
  claims: Record<string, unknown>,
  db: OpenShapeForgeDatabase | undefined,
): Promise<string | null> {
  const membership = selectOrganizationMembership(identity);
  if (!membership) {
    if (Object.keys(identity.organizations ?? {}).length > 0) {
      console.warn(
        "[auth] Bearer token carries Keycloak Organization memberships but none can be " +
          "selected (no `id` on the membership — enable \"add organization id\" on the " +
          "organization membership mapper — or several memberships without an " +
          "`organization:<alias>` scope). Tenant unresolved.",
      );
    }
    return null;
  }
  const realm = realmFromIssuer(claims.iss);
  if (!realm) {
    console.warn("[auth] Bearer token issuer is not a Keycloak realm URL; tenant unresolved.");
    return null;
  }
  if (!db && !tenantForOrganizationOverride) {
    console.warn(
      "[auth] Bearer token names its tenant by Keycloak Organization membership, but this " +
        "surface resolves sessions without a database. Tenant unresolved.",
    );
    return null;
  }

  const tenantId = await lookupTenantForOrganization(db, realm, membership.id);
  if (!tenantId) {
    console.warn(
      `[auth] No tenant is linked to Keycloak Organization "${membership.alias}" ` +
        `(${membership.id}) in realm "${realm}". Provision or reconcile it through the ` +
        "control plane. Tenant unresolved.",
    );
    return null;
  }
  return tenantId;
}

/** A human host session has exactly one selected, verified membership. Neither
 * tid, organization-specific scopes nor transport input may select another one.
 */
export async function resolveHostOrganizationTenant(
  identity: AuthIdentity,
  claims: Record<string, unknown>,
  db: OpenShapeForgeDatabase | undefined,
): Promise<string | null> {
  const raw = claims.organization;
  if (!raw || typeof raw !== "object" || Array.isArray(raw) ||
      Object.keys(raw).length !== 1 || !identity.scopes?.includes("organization")) return null;
  const memberships = Object.entries(identity.organizations ?? {});
  if (memberships.length !== 1) return null;
  const membership = memberships[0]![1];
  if (!membership.id?.trim()) return null;
  const realm = realmFromIssuer(claims.iss);
  if (!realm) return null;
  const tenantId = await lookupTenantForOrganization(db, realm, membership.id);
  if (!tenantId || (claims.tid !== undefined && !sameTenantId(
      typeof claims.tid === "string" ? claims.tid : null, tenantId))) return null;
  return tenantId;
}

/** Explicit service credentials supply the tenant authority. Verify that their
 * signed tid agrees with that credential AND its realm/organization registry row.
 * This is a tenant-scoped read, never a raw-input or cross-tenant bypass.
 */
export async function resolveScopedServiceTenant(
  identity: AuthIdentity,
  claims: Record<string, unknown>,
  credential: { tenantId: string; clientId: string },
  db: OpenShapeForgeDatabase | undefined,
): Promise<string | null> {
  const realm = realmFromIssuer(claims.iss);
  if (!db || !realm || !identity.userId ||
      !sameTenantId(identity.tenantId, credential.tenantId) ||
      claims.azp !== credential.clientId ||
      claims.preferred_username !== `service-account-${credential.clientId}`) return null;
  const row = await withDbSession(db, {
    tenantId: credential.tenantId, userId: identity.userId, roles: [], scope: "self",
  }, async (trx) => {
    const result = await sql<{ keycloak_organization_id: string | null; keycloak_realm: string | null }>`
      select keycloak_organization_id, keycloak_realm from platform.tenants
      where id = ${credential.tenantId}::uuid
    `.execute(trx);
    return result.rows[0];
  });
  if (!row?.keycloak_organization_id || row.keycloak_realm !== realm) return null;
  const tenantId = await lookupTenantForOrganization(db, realm, row.keycloak_organization_id);
  if (!sameTenantId(tenantId, credential.tenantId)) return null;
  // If a service token also carries membership, it may not contradict the credential.
  if (claims.organization !== undefined &&
      await resolveHostOrganizationTenant(identity, claims, db) !== tenantId) return null;
  return tenantId;
}

/**
 * The per-organization resource path. Membership, audience and registry are
 * checked in auth/organization-binding.ts; this is the glue to the verifier's
 * output and the database. Throws OrganizationBindingError on any refusal.
 */
export async function resolveTenantForBoundOrganization(
  identity: AuthIdentity,
  claims: Record<string, unknown>,
  binding: OrganizationResourceBinding,
  db: OpenShapeForgeDatabase | undefined,
): Promise<string> {
  const realm = realmFromIssuer(claims.iss);
  const lookup: TenantForOrganization = async (realmName, organizationId) => {
    if (!db && !tenantForOrganizationOverride) {
      throw new OrganizationBindingError(
        binding,
        "the organization resource resolves sessions without a database",
      );
    }
    return lookupTenantForOrganization(db, realmName, organizationId);
  };
  const bound = await bindOrganizationResource(identity, claims, binding, realm, lookup);
  return bound.tenantId;
}

/** Matches an `Authorization: Bearer <token>` header (case-insensitive). */
