// SPDX-License-Identifier: BUSL-1.1
/**
 * Example compiler plugin: emits a markdown overview of every generated
 * entity. Demonstrates the plugin contract — pure, manifest/contract-driven
 * generation with declared output ownership. Registered in
 * `authoring.config.yaml` under `plugins:`.
 */
import type { CompilerPlugin } from "../../packages/compiler/src/plugins.js";

const OUTPUT_PATH = "docs/entities.generated.md";

const plugin: CompilerPlugin = {
  name: "entity-docs",
  ownedPaths: { files: [OUTPUT_PATH] },

  generate({ manifest }) {
    const lines: string[] = [
      "<!-- Generated by the entity-docs example plugin. Do not edit. -->",
      "# Generated entities",
      "",
    ];

    const tables = manifest.tables
      .filter((table) => table.generatedCrud && table.source?.graphql)
      .toSorted((a, b) => `${a.schema}.${a.name}`.localeCompare(`${b.schema}.${b.name}`));

    for (const table of tables) {
      const source = table.source!;
      const graphql = source.graphql!;
      // In-memory tables carry schema and name separately; render qualified.
      lines.push(`## ${graphql.typeName} (\`${table.schema}.${table.name}\`)`);
      const label = source.labels?.en;
      if (label) {
        lines.push("", `${label} — authored in \`${source.path}\`.`);
      }
      lines.push(
        "",
        `GraphQL: \`${graphql.listQueryName}\`, \`${graphql.singleQueryName}\`, ` +
          `\`${graphql.createMutationName}\`, \`${graphql.updateMutationName}\`, ` +
          `\`${graphql.deleteMutationName}\``,
        "",
        "| column | type | required |",
        "| --- | --- | --- |",
      );
      for (const column of table.columns) {
        lines.push(`| ${column.name} | ${column.type} | ${column.required ? "yes" : ""} |`);
      }
      lines.push("");
    }

    return [{ path: OUTPUT_PATH, contents: `${lines.join("\n")}\n` }];
  },
};

export default plugin;
