// SPDX-License-Identifier: BUSL-1.1
/**
 * HAND-WRITTEN, and it must stay that way.
 *
 * `apps/web/src/app/layout.tsx` is compiler output — it is listed in
 * `compilerGeneratedAppShellFiles` and gitignored, and it carries a
 * "Generated by OpenShapeForge Service Compiler" banner. This file is its
 * opposite number and is NOT generated: `apps/admin` is outside
 * `compilerOwnedGeneratedRoots` on purpose (see issue #290), because the
 * control plane has no entity model to generate pages from and adding one
 * would make `bun run generate` responsible for an app it knows nothing about.
 *
 * Concretely: do not add a nav manifest here expecting the compiler to fill it,
 * and do not add `apps/admin` to any generated-artifact path list.
 *
 * This layout deliberately does NO authorization. It wraps `/login` and
 * `/not-authorized` as well as the console, and those two must render for a
 * visitor who has no operator session. The gate lives one level down, in
 * `(console)/layout.tsx`.
 */
import type { ReactNode } from "react";
import "./globals.css";

export const metadata = {
  title: "OpenShapeForge Control Plane",
  description: "Tenant and sub-organisation administration",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen antialiased">{children}</body>
    </html>
  );
}
