// SPDX-License-Identifier: BUSL-1.1
/**
 * The renderer's generated contract modules, emitted under
 * `apps/web/src/generated/compiler/` whenever `apps/web` exists.
 *
 * `apps/web` cannot import the compiler package (bundler resolution versus
 * NodeNext specifiers), so what it needs of the compiled contract is projected
 * into plain TypeScript modules: the field-contract types, the resolved osf
 * type catalog split by origin, the remote-lookup manifest, the component
 * defaults, the field authoring profiles, the canonical condition types, the
 * GraphQL names an entity reference picker needs to list records, and every
 * entity's readable fields for the variable and condition pickers.
 */
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";
import { buildCrud } from "../compiler/crud.js";
import { pluralize, uncapitalize } from "../compiler/helpers.js";
import { graphqlOperationActions } from "../entity-model.js";
import { withBaseTypes } from "../entity-fields.js";
import { loadOsfTypes } from "../loader.js";
import type { CoreEntity, EntityProfile, Field, OsfTypeDefinition } from "../types.js";
import { buildWebFieldContractSource } from "./web-field-contract.js";

const CANONICAL_DIR = join(import.meta.dirname, "../canonical");
const HEADER = "// Generated by OpenShapeForge Service Compiler.";
const FOOTER = "// Do not edit manually.";

type OsfTypeCatalog = { types?: Record<string, unknown> };
type ComponentCatalog = { defaults?: Record<string, unknown> };
type FieldAuthoringProfileCatalog = { profiles?: Record<string, unknown> };

type CategorizedOsfTypes = {
  core: Record<string, unknown>;
  context: Record<string, unknown>;
  entityIds: Record<string, unknown>;
};

type GraphqlRegistry = Record<string, { plural: string; filterType: string; idField: string }>;

function loadYamlFile<T>(filePath: string): T {
  return parseYaml(readFileSync(filePath, "utf-8")) as T;
}

function toKebabCase(value: string): string {
  return value.replace(/([a-z0-9])([A-Z])/g, "$1-$2").replace(/[\s_]+/g, "-").toLowerCase();
}

function generatedModule(sourceOfTruth: string, body: string[]): string {
  return [HEADER, `// Source of truth: ${sourceOfTruth}`, FOOTER, "", ...body, ""].join("\n");
}

/**
 * The GraphQL names behind an entity reference picker's list query. An entity
 * belongs here only when its list Operation is projected to GraphQL, not
 * merely implemented: a list withheld from GraphQL has no query to build.
 */
export function buildCoreEntityGraphqlRegistry(entities: readonly CoreEntity[]): GraphqlRegistry {
  const registry: GraphqlRegistry = {};
  for (const entity of entities) {
    const slug = toKebabCase(entity.entity);
    if (registry[slug]) continue;
    if (!buildCrud(entity).operations.list || !graphqlOperationActions(entity).list) continue;
    registry[slug] = {
      plural: pluralize(uncapitalize(entity.entity)),
      filterType: `${entity.entity}Filter`,
      idField: "id",
    };
  }
  return registry;
}

/**
 * An identity alias renders as an entity reference; the records a picker
 * offers come from the alias's `optionSource` (the entity's list Operation),
 * never from a web route.
 */
function enrichEntityIdOsfType(definition: unknown): unknown {
  if (!definition || typeof definition !== "object" || Array.isArray(definition)) return definition;
  const record = definition as Record<string, unknown>;
  if (record.kind !== "entityId") return definition;
  const render = record.render && typeof record.render === "object" && !Array.isArray(record.render)
    ? record.render as Record<string, unknown>
    : {};
  return {
    ...record,
    render: { display: "EntityReferenceDisplay", input: "EntityReferenceSelect", ...render },
    ...(record.optionSource && !record.options ? { options: record.optionSource } : {}),
  };
}

/**
 * The osf types split by origin: the authored core and context catalogs by the
 * YAML they came from, and the identity aliases the compiler derives per
 * entity, limited to the entities a picker can list.
 */
function loadCategorizedOsfTypes(
  osfTypes: Record<string, OsfTypeDefinition>,
  authoringDir: string,
  listableSlugs: ReadonlySet<string>,
): CategorizedOsfTypes {
  const core: Record<string, unknown> = {};
  const context: Record<string, unknown> = {};
  const entityIds: Record<string, unknown> = {};

  for (const [key, definition] of Object.entries(osfTypes)) {
    if (definition.kind !== "entityId") continue;
    if (definition.entity && !listableSlugs.has(toKebabCase(definition.entity))) continue;
    entityIds[key] = enrichEntityIdOsfType(definition);
  }

  const corePath = join(authoringDir, "catalogs", "osf-types.yaml");
  if (existsSync(corePath)) Object.assign(core, loadYamlFile<OsfTypeCatalog>(corePath).types ?? {});

  const contextsDir = join(authoringDir, "contexts");
  if (existsSync(contextsDir)) {
    for (const entry of readdirSync(contextsDir, { withFileTypes: true })) {
      if (!entry.isDirectory()) continue;
      const contextPath = join(contextsDir, entry.name, "osf-types.yaml");
      if (!existsSync(contextPath)) continue;
      Object.assign(context, loadYamlFile<OsfTypeCatalog>(contextPath).types ?? {});
    }
  }

  return { core, context, entityIds };
}

const OSF_TYPE_PARTIALS = [
  { suffix: "core", constName: "COMPILER_OSF_TYPES_CORE", source: "catalogs/osf-types.yaml", pick: (c: CategorizedOsfTypes) => c.core },
  { suffix: "context", constName: "COMPILER_OSF_TYPES_CONTEXT", source: "contexts/*/osf-types.yaml", pick: (c: CategorizedOsfTypes) => c.context },
  { suffix: "entity-ids", constName: "COMPILER_OSF_TYPES_ENTITY_IDS", source: "entities/**/*.yaml (identity aliases derived per entity, kind: entityId)", pick: (c: CategorizedOsfTypes) => c.entityIds },
] as const;

function osfTypeModules(categorized: CategorizedOsfTypes): Map<string, string> {
  const files = new Map<string, string>();
  for (const partial of OSF_TYPE_PARTIALS) {
    files.set(`osf-types-${partial.suffix}.ts`, generatedModule(`packages/compiler/config/authoring/${partial.source}`, [
      'import type { OsfTypeDefinition } from "./field-contract";',
      "",
      `export const ${partial.constName} = ${JSON.stringify(partial.pick(categorized), null, 2)} as const satisfies Record<string, OsfTypeDefinition>;`,
    ]));
  }
  files.set("osf-types.ts", generatedModule("packages/compiler/config/authoring/**/osf-types.yaml", [
    'import type { OsfTypeDefinition } from "./field-contract";',
    'import { COMPILER_OSF_TYPES_CORE } from "./osf-types-core";',
    'import { COMPILER_OSF_TYPES_CONTEXT } from "./osf-types-context";',
    'import { COMPILER_OSF_TYPES_ENTITY_IDS } from "./osf-types-entity-ids";',
    "",
    "export const COMPILER_OSF_TYPES = {",
    "  ...COMPILER_OSF_TYPES_CORE,",
    "  ...COMPILER_OSF_TYPES_CONTEXT,",
    "  ...COMPILER_OSF_TYPES_ENTITY_IDS,",
    "} as const satisfies Record<string, OsfTypeDefinition>;",
    "",
    "export type CompilerOsfTypeKey = keyof typeof COMPILER_OSF_TYPES;",
    "",
    "export const COMPILER_OSF_TYPE_KEYS = Object.keys(COMPILER_OSF_TYPES) as CompilerOsfTypeKey[];",
    "",
    'export { COMPILER_OSF_TYPES_CORE } from "./osf-types-core";',
    'export { COMPILER_OSF_TYPES_CONTEXT } from "./osf-types-context";',
    'export { COMPILER_OSF_TYPES_ENTITY_IDS } from "./osf-types-entity-ids";',
  ]));
  return files;
}

type LookupEntry = {
  osfType: string;
  provider: string;
  remoteUrl: string;
  searchParam: string;
  entity?: string;
  filters?: Record<string, string | number | boolean>;
};

function lookupFilters(value: unknown): Record<string, string | number | boolean> | undefined {
  if (!value || typeof value !== "object" || Array.isArray(value)) return undefined;
  const filters = Object.fromEntries(
    Object.entries(value).filter(([, raw]) => ["string", "number", "boolean"].includes(typeof raw)),
  ) as Record<string, string | number | boolean>;
  return Object.keys(filters).length > 0 ? filters : undefined;
}

/** Every osf type with a remote lookup provider, and where the web app asks it. */
function buildLookupManifest(categorized: CategorizedOsfTypes): Record<string, LookupEntry> {
  const lookups: Record<string, LookupEntry> = {};
  const all = { ...categorized.core, ...categorized.context, ...categorized.entityIds };
  for (const [osfType, raw] of Object.entries(all)) {
    const definition = raw as {
      entity?: string;
      lookup?: { provider?: string; remoteUrl?: string; searchParam?: string; filters?: unknown };
    };
    if (!definition.lookup?.provider) continue;
    const filters = lookupFilters(definition.lookup.filters);
    lookups[osfType] = {
      osfType,
      provider: definition.lookup.provider,
      remoteUrl: definition.lookup.remoteUrl?.trim() || `/api/runtime/lookups?osfType=${encodeURIComponent(osfType)}`,
      searchParam: definition.lookup.searchParam?.trim() || "search",
      ...(definition.entity ? { entity: definition.entity } : {}),
      ...(filters ? { filters } : {}),
    };
  }
  return lookups;
}

function lookupsModule(lookups: Record<string, LookupEntry>): string {
  return generatedModule("packages/compiler/config/authoring/**/osf-types.yaml", [
    "export interface CompilerOsfTypeLookupDefinition {",
    "  osfType: string;",
    "  provider: string;",
    "  remoteUrl: string;",
    "  searchParam: string;",
    "  entity?: string;",
    "  filters?: Record<string, string | number | boolean>;",
    "}",
    "",
    `export const COMPILER_OSF_TYPE_LOOKUPS = ${JSON.stringify(lookups, null, 2)} as const satisfies Record<string, CompilerOsfTypeLookupDefinition>;`,
    "",
    "export type CompilerOsfTypeLookupKey = keyof typeof COMPILER_OSF_TYPE_LOOKUPS;",
  ]);
}

function graphqlRegistryModule(registry: GraphqlRegistry): string {
  return generatedModule("packages/compiler/config/authoring/entity definitions", [
    "// Maps each entity's kebab-case slug to the GraphQL gateway names a",
    "// reference picker needs to build a minimal list query on the fly.",
    "",
    "export interface CoreEntityGraphqlInfo {",
    "  /** GraphQL list field name (e.g. `relations`). */",
    "  plural: string;",
    "  /** GraphQL filter input-type name (e.g. `RelationFilter`). */",
    "  filterType: string;",
    "  /** Primary-key field name on the GraphQL node. */",
    "  idField: string;",
    "}",
    "",
    `export const COMPILER_CORE_ENTITY_GRAPHQL_REGISTRY = ${JSON.stringify(registry, null, 2)} as const satisfies Record<string, CoreEntityGraphqlInfo>;`,
    "",
    "export type CoreEntityGraphqlRegistrySlug = keyof typeof COMPILER_CORE_ENTITY_GRAPHQL_REGISTRY;",
  ]);
}

function componentDefaultsModule(authoringDir: string): string {
  const path = join(authoringDir, "catalogs", "components.yaml");
  const defaults = existsSync(path) ? loadYamlFile<ComponentCatalog>(path).defaults ?? {} : {};
  return generatedModule("packages/compiler/config/authoring/catalogs/components.yaml", [
    `export const COMPILER_FIELD_COMPONENT_DEFAULTS = ${JSON.stringify(defaults, null, 2)} as const;`,
    "",
    "export type CompilerFieldTypeKey = keyof typeof COMPILER_FIELD_COMPONENT_DEFAULTS;",
  ]);
}

function fieldAuthoringProfilesModule(authoringDir: string): string {
  const path = join(authoringDir, "catalogs", "field-authoring-profiles.yaml");
  const profiles = existsSync(path) ? loadYamlFile<FieldAuthoringProfileCatalog>(path).profiles ?? {} : {};
  return generatedModule("packages/compiler/config/authoring/catalogs/field-authoring-profiles.yaml", [
    "export interface CompilerFieldAuthoringProfileDefinition {",
    "  label?: Record<string, string>;",
    "  description?: Record<string, string>;",
    "  keyBehavior?: string;",
    "  excludedFieldTypes?: string[];",
    "  typePickerUsage?: string;",
    "  controls?: Record<string, boolean | string>;",
    "  lockedVisibleProperties?: string[];",
    "  valueAuthoring?: {",
    "    label?: Record<string, string>;",
    "    description?: Record<string, string>;",
    "    component?: string;",
    "  };",
    "}",
    "",
    `export const COMPILER_FIELD_AUTHORING_PROFILES = ${JSON.stringify(profiles, null, 2)} as const satisfies Record<string, CompilerFieldAuthoringProfileDefinition>;`,
    "",
    "export type CompilerFieldAuthoringProfileKey = keyof typeof COMPILER_FIELD_AUTHORING_PROFILES;",
    "",
    "export const COMPILER_FIELD_AUTHORING_PROFILE_KEYS = Object.keys(COMPILER_FIELD_AUTHORING_PROFILES) as CompilerFieldAuthoringProfileKey[];",
  ]);
}

/** The canonical condition types, copied verbatim minus the source preamble. */
function canonicalConditionModule(): string {
  const raw = readFileSync(join(CANONICAL_DIR, "canonical-condition.ts"), "utf-8");
  const body = raw.replace(
    /^\/\/ Source file for canonical condition \/ expression TypeScript types\.[\s\S]*?Keep it self-contained — no imports\.\n/,
    "",
  );
  return generatedModule("packages/compiler/src/authoring/canonical/canonical-condition.ts", [body.trimEnd()]);
}

/** What a picker needs of a field: its key, type, shape and options — not its storage or policy. */
function pickerField(field: Field): Field {
  return {
    key: field.key,
    osfType: field.osfType,
    ...(field.baseType ? { baseType: field.baseType } : {}),
    ...(field.cardinality ? { cardinality: field.cardinality } : {}),
    label: field.label,
    ...(field.validation ? { validation: field.validation } : {}),
    ...(field.options ? { options: field.options } : {}),
    ...(field.children?.length ? { children: field.children.map(pickerField) } : {}),
    ...(field.item ? { item: pickerField(field.item) } : {}),
  } as Field;
}

/** The tenant column is the fence, not a value anyone selects. */
const isTenantField = (field: Field) => field.key === "tenantId" || field.osfType === "tenantId";

/** An entity as a host composes it: the core entity and its context partials. */
export type ComposedEntity = { entity: CoreEntity; profiles: readonly EntityProfile[] };

/**
 * The context-complete field set of an entity: its own normalized fields
 * followed by every context partial's, each with its base type derived.
 */
export function composedEntityFields({ entity, profiles }: ComposedEntity, osfTypes: Record<string, OsfTypeDefinition>): Field[] {
  const own = new Set(entity.fields.map((field) => field.key));
  const partial = profiles.flatMap((profile) =>
    withBaseTypes(profile.fields ?? [], osfTypes, `${entity.entity}[${profile.profile}]`, { entityReferences: "normalizedLater" })
      .filter((field) => !own.has(field.key)));
  return [...entity.fields, ...partial].filter((field) => !isTenantField(field));
}

/**
 * Every entity's readable fields, keyed by entity name, for the renderer's
 * entity-field variable source (label rules, condition builders). Context
 * partials' fields belong to the entity a host sees, so they come along;
 * nested shapes do too; the tenant field does not.
 */
function entityFieldsModule(entities: readonly ComposedEntity[], osfTypes: Record<string, OsfTypeDefinition>): string {
  const byEntity: Record<string, Field[]> = {};
  for (const composed of [...entities].sort((left, right) => left.entity.entity.localeCompare(right.entity.entity))) {
    byEntity[composed.entity.entity] = composedEntityFields(composed, osfTypes).map(pickerField);
  }
  return generatedModule("packages/compiler/config/authoring/entities/**/*.yaml", [
    'import type { Field } from "./field-contract";',
    "",
    "// A JSON.parse string rather than an object literal, so TypeScript does not",
    "// infer a multi-megabyte literal type during `tsc --noEmit`.",
    `export const COMPILER_ENTITY_FIELDS = JSON.parse(${JSON.stringify(JSON.stringify(byEntity))}) as Record<string, Field[]>;`,
  ]);
}

/**
 * Every module of the renderer contract, keyed by file name; the caller
 * places them under the web app's generated compiler directory.
 */
export function generateWebContractModules(authoringDir: string, composed: readonly ComposedEntity[]): Map<string, string> {
  const entities = composed.map(({ entity }) => entity);
  const osfTypes = loadOsfTypes(authoringDir);
  const registry = buildCoreEntityGraphqlRegistry(entities);
  const categorized = loadCategorizedOsfTypes(osfTypes, authoringDir, new Set(Object.keys(registry)));
  const files = new Map<string, string>([
    ["field-contract.ts", buildWebFieldContractSource()],
    ["component-defaults.ts", componentDefaultsModule(authoringDir)],
    ["field-authoring-profiles.ts", fieldAuthoringProfilesModule(authoringDir)],
    ["canonical-condition.ts", canonicalConditionModule()],
    ["core-entity-graphql-registry.ts", graphqlRegistryModule(registry)],
    ["osf-type-lookups.ts", lookupsModule(buildLookupManifest(categorized))],
    ["entity-fields.ts", entityFieldsModule(composed, osfTypes)],
  ]);
  for (const [name, contents] of osfTypeModules(categorized)) files.set(name, contents);
  return files;
}
