// SPDX-License-Identifier: BUSL-1.1
import { sql, type Kysely } from "kysely";
import type { VersionedMigration } from "../versioned-runner.js";

/**
 * 0002_org-unit-closure-trigger
 *
 * Installs the transitive-closure maintenance trigger for
 * platform.org_unit → platform.org_unit_closure (group-predicated RLS, §D.2).
 *
 * Sequencing: versioned migrations run BEFORE the generated roll-forward, so
 * platform.org_unit / platform.org_unit_closure may not exist yet on a fresh
 * install. We therefore create both tables here with `CREATE TABLE IF NOT
 * EXISTS`, mirroring the generated shape EXACTLY — the generated roll-forward
 * that follows sees them already present and no-ops (its diff stays additive).
 * This lets the trigger attach before any org_unit row is ever inserted (seed
 * or otherwise), keeping the closure correct for the very first insert.
 *
 * The trigger function is SECURITY DEFINER (owned by the privileged migrate
 * role) so its closure DML is not blocked by RLS on org_unit_closure, while it
 * always writes tenant_id straight from NEW/OLD (never cross-tenant — asserted
 * on UPDATE). DELETE of a parent with children is blocked by the parent_id FK
 * ON DELETE RESTRICT (declared in platform-schema.yaml); on a leaf delete the
 * trigger tears down that node's closure edges.
 *
 * Applied migrations are immutable: the sha256 of THIS FILE is recorded in
 * platform.schema_migrations and re-verified on every migrate run. Once this
 * migration has been applied anywhere, do not edit this file — scaffold a new
 * migration instead (bun run db:migration:new <name>).
 */
const migration: VersionedMigration = {
  version: "0002_org-unit-closure-trigger",
  fileUrl: import.meta.url,
  // Commit 8aa19b2 added the SPDX header line to this already-applied
  // migration, and this entry itself changed the hash again. Neither edit
  // touched a statement the database observes, so environments holding an
  // earlier hash are reconciled rather than wedged. Ordered oldest first:
  // initial release, then post-header.
  supersededChecksums: [
    "d90d49881b7942491b46eb75121b77fb2e614d1c2a82a86aea4af1a70ad7b92a",
    "057e047c26b4b70edee825e6b967f8883209ccc7c2ebf572e79630f9015eb05e",
  ],
  async up(db: Kysely<any>): Promise<void> {
    // ── Tables (IF NOT EXISTS; generated roll-forward re-declares identically) ──
    await sql`
      create table if not exists platform.org_unit (
        "id" uuid primary key not null default gen_random_uuid(),
        "tenant_id" uuid not null,
        "parent_id" uuid,
        "name" text not null,
        "created_at" timestamptz not null default now(),
        "updated_at" timestamptz not null default now()
      )
    `.execute(db);
    await sql`
      create table if not exists platform.org_unit_closure (
        "id" uuid primary key not null default gen_random_uuid(),
        "tenant_id" uuid not null,
        "ancestor_id" uuid not null,
        "descendant_id" uuid not null,
        "depth" integer not null
      )
    `.execute(db);

    // ── Closure maintenance function ──────────────────────────────────────────
    // INSERT: self-row (NEW.id, NEW.id, 0) + copy parent's ancestor paths +1.
    // UPDATE of parent_id: standard closure reparent — delete edges that link
    //   the moved subtree to its OLD ancestors (crossing the moved node), then
    //   reinsert the cross-product of the NEW parent's ancestor paths × the
    //   moved subtree. Assert the tenant never changes.
    // DELETE: remove every closure edge that touches the deleted node. The
    //   parent_id FK (ON DELETE RESTRICT) blocks deleting a unit that still has
    //   children, so a deleted node is always a leaf w.r.t. org_unit rows.
    await sql`
      create or replace function platform.org_unit_closure_maintain()
      returns trigger
      language plpgsql
      security definer
      set search_path = platform, pg_temp
      as $fn$
      begin
        if tg_op = 'INSERT' then
          -- Self-row at depth 0.
          insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
          values (new.tenant_id, new.id, new.id, 0);
          -- Inherit the parent's ancestors, one level deeper.
          if new.parent_id is not null then
            insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
            select c.tenant_id, c.ancestor_id, new.id, c.depth + 1
            from platform.org_unit_closure c
            where c.tenant_id = new.tenant_id
              and c.descendant_id = new.parent_id;
          end if;
          return new;

        elsif tg_op = 'UPDATE' then
          if new.tenant_id <> old.tenant_id then
            raise exception 'org_unit.tenant_id is immutable (% -> %)', old.tenant_id, new.tenant_id;
          end if;
          if new.parent_id is distinct from old.parent_id then
            -- The subtree rooted at the moved node (its self + all descendants).
            -- Delete edges linking that subtree to any ancestor OUTSIDE the
            -- subtree (i.e. the old cross-boundary paths).
            delete from platform.org_unit_closure
            where tenant_id = new.tenant_id
              and descendant_id in (
                select descendant_id from platform.org_unit_closure
                where tenant_id = new.tenant_id and ancestor_id = new.id
              )
              and ancestor_id not in (
                select descendant_id from platform.org_unit_closure
                where tenant_id = new.tenant_id and ancestor_id = new.id
              );
            -- Reinsert the cross-product: NEW parent's ancestor paths ×
            -- the moved subtree, summing depths across the new join point.
            if new.parent_id is not null then
              insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
              select super.tenant_id, super.ancestor_id, sub.descendant_id, super.depth + sub.depth + 1
              from platform.org_unit_closure super
              cross join platform.org_unit_closure sub
              where super.tenant_id = new.tenant_id
                and super.descendant_id = new.parent_id
                and sub.tenant_id = new.tenant_id
                and sub.ancestor_id = new.id;
            end if;
          end if;
          return new;

        elsif tg_op = 'DELETE' then
          -- Tear down every edge that references the deleted node. The FK
          -- RESTRICT guarantees it has no child org_unit rows.
          delete from platform.org_unit_closure
          where tenant_id = old.tenant_id
            and (ancestor_id = old.id or descendant_id = old.id);
          return old;
        end if;
        return null;
      end;
      $fn$;
    `.execute(db);

    // ── Trigger (row-level, fires after the write so NEW.id exists) ───────────
    await sql`drop trigger if exists org_unit_closure_maintain_trg on platform.org_unit`.execute(db);
    await sql`
      create trigger org_unit_closure_maintain_trg
      after insert or update or delete on platform.org_unit
      for each row execute function platform.org_unit_closure_maintain()
    `.execute(db);
  },
};

export default migration;
