// SPDX-License-Identifier: BUSL-1.1
import { sql, type Kysely } from "kysely";
import type { VersionedMigration } from "../versioned-runner.js";

/**
 * 0003_org-unit-parent-tenant-guard
 *
 * Hardens the closure-maintenance trigger installed by
 * 0002_org-unit-closure-trigger against a cross-tenant / dangling parent_id.
 *
 * The self-referential FK on platform.org_unit(parent_id) references
 * platform.org_unit(id) WITHOUT a tenant qualifier (it cannot carry one: the
 * PK it targets is (id) alone), so parent_id may point at an org_unit row in a
 * DIFFERENT tenant — or, on a stale write, at an id that does not exist under
 * the row's own tenant. The FK still passes (the id exists somewhere) and the
 * tenant_isolation RLS WITH CHECK only validates the row's own tenant_id, not
 * parent_id. The old trigger then inherited the parent's ancestor paths with
 * `where c.tenant_id = new.tenant_id and c.descendant_id = new.parent_id`;
 * with a foreign-tenant parent that filter matched zero rows, so the node was
 * written with ONLY its self-edge — a silent phantom root whose parent_id
 * dangles across the tenant boundary, diverging the stored closure from
 * parent_id (issue #15 / M-04).
 *
 * This migration replaces platform.org_unit_closure_maintain() so that, on
 * INSERT and on a reparenting UPDATE, a non-null parent_id MUST resolve to a
 * same-tenant closure self-row (which exists iff a same-tenant org_unit with
 * that id exists — every org_unit gets its (id,id,0) self-edge on insert).
 * Otherwise the trigger RAISEs, aborting the write. The check keys off the
 * closure self-row rather than org_unit directly so it runs under the
 * SECURITY DEFINER function's privileges without depending on the caller's RLS
 * visibility of sibling org_unit rows. All other behaviour (self-row,
 * inheritance, reparent cross-product, tenant immutability, delete teardown)
 * is preserved verbatim from 0002.
 *
 * Forward-only: CREATE OR REPLACE FUNCTION rebinds the existing trigger's
 * target in place, so no trigger DROP/CREATE is needed and re-running the
 * chain is idempotent.
 *
 * Applied migrations are immutable: the sha256 of THIS FILE is recorded in
 * platform.schema_migrations and re-verified on every migrate run. Once this
 * migration has been applied anywhere, do not edit this file — scaffold a new
 * migration instead (bun run db:migration:new <name>).
 */
const migration: VersionedMigration = {
  version: "0003_org-unit-parent-tenant-guard",
  fileUrl: import.meta.url,
  async up(db: Kysely<any>): Promise<void> {
    await sql`
      create or replace function platform.org_unit_closure_maintain()
      returns trigger
      language plpgsql
      security definer
      set search_path = platform, pg_temp
      as $fn$
      begin
        if tg_op = 'INSERT' then
          -- A non-null parent must reference a same-tenant org_unit. Its
          -- closure self-row (parent_id, parent_id, 0) exists iff such a row
          -- exists in this tenant; its absence means the FK was satisfied by a
          -- foreign-tenant (or otherwise unreachable) id. Fail loudly rather
          -- than silently writing a phantom root.
          if new.parent_id is not null and not exists (
            select 1 from platform.org_unit_closure c
            where c.tenant_id = new.tenant_id
              and c.ancestor_id = new.parent_id
              and c.descendant_id = new.parent_id
              and c.depth = 0
          ) then
            raise exception
              'org_unit.parent_id % is not a valid parent in tenant % (cross-tenant or nonexistent parent)',
              new.parent_id, new.tenant_id;
          end if;
          -- Self-row at depth 0.
          insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
          values (new.tenant_id, new.id, new.id, 0);
          -- Inherit the parent's ancestors, one level deeper.
          if new.parent_id is not null then
            insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
            select c.tenant_id, c.ancestor_id, new.id, c.depth + 1
            from platform.org_unit_closure c
            where c.tenant_id = new.tenant_id
              and c.descendant_id = new.parent_id;
          end if;
          return new;

        elsif tg_op = 'UPDATE' then
          if new.tenant_id <> old.tenant_id then
            raise exception 'org_unit.tenant_id is immutable (% -> %)', old.tenant_id, new.tenant_id;
          end if;
          if new.parent_id is distinct from old.parent_id then
            -- Same same-tenant-parent guard as on INSERT: a reparent onto a
            -- cross-tenant or nonexistent parent must abort, not silently
            -- detach the subtree into a phantom root.
            if new.parent_id is not null and not exists (
              select 1 from platform.org_unit_closure c
              where c.tenant_id = new.tenant_id
                and c.ancestor_id = new.parent_id
                and c.descendant_id = new.parent_id
                and c.depth = 0
            ) then
              raise exception
                'org_unit.parent_id % is not a valid parent in tenant % (cross-tenant or nonexistent parent)',
                new.parent_id, new.tenant_id;
            end if;
            -- The subtree rooted at the moved node (its self + all descendants).
            -- Delete edges linking that subtree to any ancestor OUTSIDE the
            -- subtree (i.e. the old cross-boundary paths).
            delete from platform.org_unit_closure
            where tenant_id = new.tenant_id
              and descendant_id in (
                select descendant_id from platform.org_unit_closure
                where tenant_id = new.tenant_id and ancestor_id = new.id
              )
              and ancestor_id not in (
                select descendant_id from platform.org_unit_closure
                where tenant_id = new.tenant_id and ancestor_id = new.id
              );
            -- Reinsert the cross-product: NEW parent's ancestor paths ×
            -- the moved subtree, summing depths across the new join point.
            if new.parent_id is not null then
              insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
              select super.tenant_id, super.ancestor_id, sub.descendant_id, super.depth + sub.depth + 1
              from platform.org_unit_closure super
              cross join platform.org_unit_closure sub
              where super.tenant_id = new.tenant_id
                and super.descendant_id = new.parent_id
                and sub.tenant_id = new.tenant_id
                and sub.ancestor_id = new.id;
            end if;
          end if;
          return new;

        elsif tg_op = 'DELETE' then
          -- Tear down every edge that references the deleted node. The FK
          -- RESTRICT guarantees it has no child org_unit rows.
          delete from platform.org_unit_closure
          where tenant_id = old.tenant_id
            and (ancestor_id = old.id or descendant_id = old.id);
          return old;
        end if;
        return null;
      end;
      $fn$;
    `.execute(db);
  },
};

export default migration;
