// SPDX-License-Identifier: BUSL-1.1
import { sql, type Kysely } from "kysely";
import type { VersionedMigration } from "../versioned-runner.js";

/**
 * 0004_org-unit-reparent-cycle-guard
 *
 * Hardens the closure-maintenance trigger installed by
 * 0002_org-unit-closure-trigger against a reparent that would create a cycle.
 *
 * The reparent branch (parent_id changed) never checked that the new parent
 * lies OUTSIDE the moved subtree. Moving node X under one of X's own
 * descendants D is not blocked by the self-referential FK (it is
 * tenant-agnostic and only requires the id to exist) nor by any application
 * guard. The reinsert cross-product then joins the new parent's ancestor paths
 * (which include X, since X is an ancestor of D) against X's subtree (which
 * includes X's self-row), emitting an (X, X, depth>=2) edge that collides with
 * the existing (X, X, 0) self-row under org_unit_closure_edge_uk. The move
 * therefore aborted with a raw "duplicate key value violates unique constraint
 * org_unit_closure_edge_uk" — an opaque error that gives no hint that a cycle
 * was attempted, and correctness rested entirely on that unique index existing
 * (issue #32 / L-04).
 *
 * This migration replaces platform.org_unit_closure_maintain() so that a
 * reparenting UPDATE first checks whether new.parent_id is inside the moved
 * subtree (a same-tenant closure edge ancestor_id = new.id,
 * descendant_id = new.parent_id) and RAISEs a clear "would create a cycle"
 * error, instead of relying on the unique index as an accidental cycle guard.
 * It also carries forward 0003's same-tenant-parent guard (a non-null
 * parent_id must resolve to a same-tenant closure self-row on both INSERT and
 * reparent) so this CREATE OR REPLACE does not regress the cross-tenant
 * phantom-root fix. All other behaviour (self-row, inheritance, reparent
 * cross-product, tenant immutability, delete teardown) is preserved from 0002.
 *
 * Forward-only: CREATE OR REPLACE FUNCTION rebinds the existing trigger's
 * target in place, so no trigger DROP/CREATE is needed and re-running the
 * chain is idempotent.
 *
 * Applied migrations are immutable: the sha256 of THIS FILE is recorded in
 * platform.schema_migrations and re-verified on every migrate run. Once this
 * migration has been applied anywhere, do not edit this file — scaffold a new
 * migration instead (bun run db:migration:new <name>).
 */
const migration: VersionedMigration = {
  version: "0004_org-unit-reparent-cycle-guard",
  fileUrl: import.meta.url,
  // Commit 8aa19b2 added the SPDX header line to this already-applied
  // migration, and this entry itself changed the hash again. Neither edit
  // touched a statement the database observes, so environments holding an
  // earlier hash are reconciled rather than wedged. Ordered oldest first:
  // initial release, then post-header.
  supersededChecksums: [
    "0ec1a786892632cb98cd86c5fe340c56c2e400e2c5ef4a8b0e2fe0b62982d7a9",
    "696c3355654bdc81c98766b19e742336edb1c2e3f886972785bf42c37222b894",
  ],
  async up(db: Kysely<any>): Promise<void> {
    await sql`
      create or replace function platform.org_unit_closure_maintain()
      returns trigger
      language plpgsql
      security definer
      set search_path = platform, pg_temp
      as $fn$
      begin
        if tg_op = 'INSERT' then
          -- A non-null parent must reference a same-tenant org_unit (from
          -- 0003). Its closure self-row (parent_id, parent_id, 0) exists iff
          -- such a row exists in this tenant; its absence means the FK was
          -- satisfied by a foreign-tenant (or otherwise unreachable) id. Fail
          -- loudly rather than silently writing a phantom root.
          if new.parent_id is not null and not exists (
            select 1 from platform.org_unit_closure c
            where c.tenant_id = new.tenant_id
              and c.ancestor_id = new.parent_id
              and c.descendant_id = new.parent_id
              and c.depth = 0
          ) then
            raise exception
              'org_unit.parent_id % is not a valid parent in tenant % (cross-tenant or nonexistent parent)',
              new.parent_id, new.tenant_id;
          end if;
          -- Self-row at depth 0.
          insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
          values (new.tenant_id, new.id, new.id, 0);
          -- Inherit the parent's ancestors, one level deeper.
          if new.parent_id is not null then
            insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
            select c.tenant_id, c.ancestor_id, new.id, c.depth + 1
            from platform.org_unit_closure c
            where c.tenant_id = new.tenant_id
              and c.descendant_id = new.parent_id;
          end if;
          return new;

        elsif tg_op = 'UPDATE' then
          if new.tenant_id <> old.tenant_id then
            raise exception 'org_unit.tenant_id is immutable (% -> %)', old.tenant_id, new.tenant_id;
          end if;
          if new.parent_id is distinct from old.parent_id then
            -- Same same-tenant-parent guard as on INSERT (from 0003): a
            -- reparent onto a cross-tenant or nonexistent parent must abort,
            -- not silently detach the subtree into a phantom root.
            if new.parent_id is not null and not exists (
              select 1 from platform.org_unit_closure c
              where c.tenant_id = new.tenant_id
                and c.ancestor_id = new.parent_id
                and c.descendant_id = new.parent_id
                and c.depth = 0
            ) then
              raise exception
                'org_unit.parent_id % is not a valid parent in tenant % (cross-tenant or nonexistent parent)',
                new.parent_id, new.tenant_id;
            end if;
            -- Reparent cycle guard: the new parent must not lie within the
            -- moved subtree. If new.parent_id is a descendant of new.id, the
            -- move would make the node its own ancestor. Fail loudly rather
            -- than aborting later with an opaque unique-constraint violation.
            if new.parent_id is not null and exists (
              select 1 from platform.org_unit_closure c
              where c.tenant_id = new.tenant_id
                and c.ancestor_id = new.id
                and c.descendant_id = new.parent_id
            ) then
              raise exception
                'org_unit reparent would create a cycle: parent % is within the subtree of %',
                new.parent_id, new.id;
            end if;
            -- The subtree rooted at the moved node (its self + all descendants).
            -- Delete edges linking that subtree to any ancestor OUTSIDE the
            -- subtree (i.e. the old cross-boundary paths).
            delete from platform.org_unit_closure
            where tenant_id = new.tenant_id
              and descendant_id in (
                select descendant_id from platform.org_unit_closure
                where tenant_id = new.tenant_id and ancestor_id = new.id
              )
              and ancestor_id not in (
                select descendant_id from platform.org_unit_closure
                where tenant_id = new.tenant_id and ancestor_id = new.id
              );
            -- Reinsert the cross-product: NEW parent's ancestor paths ×
            -- the moved subtree, summing depths across the new join point.
            if new.parent_id is not null then
              insert into platform.org_unit_closure (tenant_id, ancestor_id, descendant_id, depth)
              select super.tenant_id, super.ancestor_id, sub.descendant_id, super.depth + sub.depth + 1
              from platform.org_unit_closure super
              cross join platform.org_unit_closure sub
              where super.tenant_id = new.tenant_id
                and super.descendant_id = new.parent_id
                and sub.tenant_id = new.tenant_id
                and sub.ancestor_id = new.id;
            end if;
          end if;
          return new;

        elsif tg_op = 'DELETE' then
          -- Tear down every edge that references the deleted node. The FK
          -- RESTRICT guarantees it has no child org_unit rows.
          delete from platform.org_unit_closure
          where tenant_id = old.tenant_id
            and (ancestor_id = old.id or descendant_id = old.id);
          return old;
        end if;
        return null;
      end;
      $fn$;
    `.execute(db);
  },
};

export default migration;
