// SPDX-License-Identifier: BUSL-1.1
import { sql, type Kysely } from "kysely";
import type { VersionedMigration } from "../versioned-runner.js";

/**
 * 0005_org-unit-keycloak-link
 *
 * Adds platform.org_unit."slug" and platform.org_unit."keycloak_organization_id",
 * declared alongside the rest of that table in platform-schema.yaml.
 *
 * Both columns are nullable, so on an EXISTING database the generated
 * roll-forward would classify them as additive and add them itself. This
 * migration exists for the fresh-install path, where it would not:
 * 0002_org-unit-closure-trigger creates platform.org_unit itself with
 * `create table if not exists` — it has to, because the closure trigger must
 * attach before the first row is ever inserted, and versioned migrations run
 * before the generated step. The fresh-install branch of generated-schema.ts
 * then applies schema.sql verbatim with no ADD COLUMN pass ("no row -> apply
 * schema.sql, record the checksum"), and schema.sql's own `CREATE TABLE IF NOT
 * EXISTS` no-ops against the table 0002 already made. The two columns would
 * silently never exist on a fresh database while an upgraded one had them.
 * Adding them here — after 0002, before the generated step — makes both paths
 * land on the same shape, and is why this is a migration and not a YAML edit
 * alone.
 *
 * `add column if not exists` keeps it a no-op wherever a roll-forward already
 * added them. Nothing else about org_unit changes: the closure trigger reads
 * only id/tenant_id/parent_id, so its contract (self-row on insert, reparent
 * cross-product, tenant immutability, delete teardown) is untouched.
 *
 * platform.tenants, added in the same change, needs no migration: it is a new
 * table, which both the fresh install (schema.sql) and the roll-forward
 * (missing manifest table -> additive) create on their own.
 *
 * Applied migrations are immutable: the sha256 of THIS FILE is recorded in
 * platform.schema_migrations and re-verified on every migrate run. Once this
 * migration has been applied anywhere, do not edit this file — scaffold a new
 * migration instead (bun run db:migration:new <name>).
 */
const migration: VersionedMigration = {
  version: "0005_org-unit-keycloak-link",
  fileUrl: import.meta.url,
  async up(db: Kysely<any>): Promise<void> {
    await sql`
      alter table platform.org_unit
        add column if not exists "slug" text
    `.execute(db);
    await sql`
      alter table platform.org_unit
        add column if not exists "keycloak_organization_id" text
    `.execute(db);
  },
};

export default migration;
