// SPDX-License-Identifier: BUSL-1.1
import { sql, type Kysely } from "kysely";
import type { VersionedMigration } from "../versioned-runner.js";

/**
 * 0006_workflow-node-category-localized
 *
 * Retypes platform.workflow_node_catalog_entries."category" from text to jsonb.
 *
 * `category` is the workflow palette's group heading. It was a bare string,
 * beside `label` and `description` which are locale maps, so it was the one
 * piece of text on that screen that could not follow the reader's locale
 * (#260). It is declared jsonb in the workflow plugin's table definition as of
 * this change, and a type change is non-additive — the generated roll-forward
 * refuses it by design, so the transformation happens here, before it runs.
 *
 * The existing text is carried over as `{"en": <text>}` rather than dropped.
 * That is the same reading the compiler gives a bare-string `category` in a
 * pack authored before this change, and the one the palette already applied in
 * practice, since it capitalised the string and showed it untranslated. Every
 * row is then rewritten by its catalog seed later in the same `db:migrate` —
 * the seed checksums move with the authored values — so the backfill is what
 * covers a slice whose generated document is absent, which is exactly the row
 * nothing else would repair.
 *
 * `using` is required: Postgres has no assignment cast from text to jsonb, so
 * a plain `alter column ... type jsonb` errors rather than reinterpreting.
 * `to_jsonb("category")` would yield a jsonb *string* (`"flow"`) — valid jsonb,
 * unreadable as a locale map — so the object is built explicitly. The default
 * is dropped first because `'{}'::jsonb` cannot be cast back to the old text
 * type while the column still has it.
 *
 * Conditional on the live column type, not run blind: versioned migrations run
 * ahead of the generated roll-forward, so on a fresh install this table does
 * not exist yet (schema.sql creates it with the jsonb column already), and on a
 * database that has already been through this migration the column is jsonb.
 * Both are no-ops.
 *
 * Applied migrations are immutable: the sha256 of THIS FILE is recorded in
 * platform.schema_migrations and re-verified on every migrate run. Once this
 * migration has been applied anywhere, do not edit this file — scaffold a new
 * migration instead (bun run db:migration:new <name>).
 */
const migration: VersionedMigration = {
  version: "0006_workflow-node-category-localized",
  fileUrl: import.meta.url,
  async up(db: Kysely<any>): Promise<void> {
    const live = await sql<{ data_type: string }>`
      select data_type
      from information_schema.columns
      where table_schema = 'platform'
        and table_name = 'workflow_node_catalog_entries'
        and column_name = 'category'
    `.execute(db);

    const dataType = live.rows[0]?.data_type;
    if (dataType === undefined || dataType === "jsonb") return;

    await sql`
      alter table platform.workflow_node_catalog_entries
        alter column "category" drop default
    `.execute(db);
    await sql`
      alter table platform.workflow_node_catalog_entries
        alter column "category" type jsonb
        using jsonb_build_object('en', "category")
    `.execute(db);
    await sql`
      alter table platform.workflow_node_catalog_entries
        alter column "category" set default '{}'::jsonb
    `.execute(db);
  },
};

export default migration;
