// SPDX-License-Identifier: BUSL-1.1
import { sql, type Kysely } from "kysely";
import type { VersionedMigration } from "../versioned-runner.js";

/**
 * 0009_billing-run-item-period-optional
 *
 * Relaxes erp.billing_run_items.period_start/period_end from NOT NULL to
 * nullable. A mode = milestone BillingRunItem bills a single triggered
 * AgreementMilestone rather than a time period, so it has no period to
 * record; forcing a fake period onto it would be misleading. The generated
 * roll-forward treats a nullability change — in either direction — as
 * non-additive drift, so it is applied here first.
 *
 * Conditional on the live column, not run blind: versioned migrations run
 * ahead of the generated roll-forward, so on a fresh install this table does
 * not exist yet (schema.sql creates it already nullable), and on a database
 * that has already been through this migration the columns are nullable.
 * Both are no-ops.
 *
 * Applied migrations are immutable: the sha256 of THIS FILE is recorded in
 * platform.schema_migrations and re-verified on every migrate run. Once
 * this migration has been applied anywhere, do not edit this file —
 * scaffold a new migration instead (bun run db:migration:new <name>).
 */
const migration: VersionedMigration = {
  version: "0009_billing-run-item-period-optional",
  fileUrl: import.meta.url,
  async up(db: Kysely<any>): Promise<void> {
    const live = await sql<{ column_name: string; is_nullable: string }>`
      select column_name, is_nullable
      from information_schema.columns
      where table_schema = 'erp'
        and table_name = 'billing_run_items'
        and column_name in ('period_start', 'period_end')
    `.execute(db);

    const notNullColumns = new Set(
      live.rows.filter((row) => row.is_nullable === "NO").map((row) => row.column_name),
    );
    if (notNullColumns.has("period_start")) {
      await sql`alter table erp.billing_run_items alter column period_start drop not null`
        .execute(db);
    }
    if (notNullColumns.has("period_end")) {
      await sql`alter table erp.billing_run_items alter column period_end drop not null`
        .execute(db);
    }
  },
};

export default migration;
