// @ts-nocheck
import type { Field } from "../../../../../packages/compiler/src/authoring/types.js";
import type { WorkflowAction } from "./types.js";
import { ACTION_ICON_NAMES } from "./types.js";
import { getActionDescription, getActionLabel } from "./labels.js";
import { buildConfigFieldsWithErrorRoutesSource } from "./action-config-source.js";

export function buildActionSource(input: {
  action: WorkflowAction;
  constPrefix: string;
  definitionName: string;
  nodeType: string;
  entityLabels: { en: string; nl: string };
  readableFields: Field[];
  defaultSort?: { field: string; direction: "asc" | "desc" };
}) {
  const {
    action,
    constPrefix,
    definitionName,
    nodeType,
    entityLabels,
    readableFields,
    defaultSort,
  } = input;
  const iconName = ACTION_ICON_NAMES[action];
  const sharedImport = action === "wait"
    ? [
        `${constPrefix}CategoryLabel`,
        `${constPrefix}RecordIdField`,
        `${constPrefix}WaitConditionField`,
        `${constPrefix}WaitEventTypeField`,
        `${constPrefix}WaitOutputFields`,
        `${constPrefix}WaitTimeoutField`,
      ]
    : action === "awaitAction"    ? [
        `${constPrefix}CategoryLabel`,
        `${constPrefix}RecordIdField`,
      ]
    : [
    `${constPrefix}CategoryLabel`,
    `${constPrefix}DeleteOutputFields`,
    `${constPrefix}ListOutputFields`,
    `${constPrefix}ReadableFields`,
    `${constPrefix}RecordIdField`,
    `${constPrefix}WritableFields`,
    `${constPrefix}WritableFieldsOptional`,
      ];
  const actionLabel = getActionLabel(entityLabels, action);
  const actionDescription = getActionDescription(entityLabels, action);

  const listDefaultSortLiteral = defaultSort
    ? `, sort: { field: ${JSON.stringify(defaultSort.field)}, direction: ${JSON.stringify(defaultSort.direction)} }`
    : "";

  const defaultConfigSource =
    action === "wait"
      ? '{ eventType: "updated", timeout: "" }'
      : action === "awaitAction"
      ? '{ actions: [], timeout: "" }'
      : action === "create" || action === "update"
      ? "{ values: {} }"
      : action === "list"
        ? `{ limit: 25, filterCondition: { kind: "group", mode: "all", conditions: [] }${listDefaultSortLiteral} }`
        : "{}";

  const outputFieldsSource =
    action === "wait"
      ? `${constPrefix}WaitOutputFields`
      : action === "awaitAction"      ? "[]"
      : action === "delete"
      ? `${constPrefix}DeleteOutputFields`
      : action === "list"
        ? `${constPrefix}ListOutputFields`
        : `${constPrefix}ReadableFields`;

  const configFieldsWithErrorRoutesSource = buildConfigFieldsWithErrorRoutesSource({
    action,
    constPrefix,
    readableFields,
    defaultSort,
  });

  if (action === "wait") {
    return [
      "// Generated by OpenShapeForge Service Compiler.",
      "// Do not edit manually.",
      "",
      `import { ${iconName} } from "lucide-react";`,
      'import type { WorkflowNodeDefinition } from "../../../shared/types";',
      `import {`,
      ...sharedImport.map((item) => `  ${item},`),
      '} from "./shared";',
      "",
      `export const ${definitionName}: WorkflowNodeDefinition = {`,
      `  type: ${JSON.stringify(nodeType)},`,
      `  category: ${constPrefix}CategoryLabel,`,
      `  label: ${JSON.stringify(actionLabel.nl)},`,
      `  description: ${JSON.stringify(actionDescription.nl)},`,
      `  icon: ${iconName},`,
      `  configFields: ${configFieldsWithErrorRoutesSource},`,
      `  defaultConfig: ${defaultConfigSource},`,
      "  getOutputHandles: (config) => [",
      '    { id: "default", label: "Volgende" },',
      "    ...(typeof config.timeout === \"string\" && config.timeout.trim().length > 0",
      '      ? [{ id: "timeout", label: "Time-out" }]',
      "      : []),",
      "  ],",
      `  getOutputFields: () => ${outputFieldsSource},`,
      `};`,
      "",
    ].join("\n");
  }

  if (action === "awaitAction") {
    return [
      "// Generated by OpenShapeForge Service Compiler.",
      "// Do not edit manually.",
      "",
      `import { ${iconName} } from "lucide-react";`,
      'import type { WorkflowNodeDefinition } from "../../../shared/types";',
      `import {`,
      ...sharedImport.map((item) => `  ${item},`),
      '} from "./shared";',
      "",
      `export const ${definitionName}: WorkflowNodeDefinition = {`,
      `  type: ${JSON.stringify(nodeType)},`,
      `  category: ${constPrefix}CategoryLabel,`,
      `  label: ${JSON.stringify(actionLabel.nl)},`,
      `  description: ${JSON.stringify(actionDescription.nl)},`,
      `  icon: ${iconName},`,
      `  configFields: ${configFieldsWithErrorRoutesSource},`,
      `  defaultConfig: ${defaultConfigSource},`,
      "  getOutputHandles: (config) => {",
      "    const handles = [",
      '      { id: "default", label: "Volgende (direct)" },',
      "    ];",
      "    const actions = Array.isArray(config.actions) ? config.actions : [];",
      "    for (const action of actions) {",
      "      if (typeof action?.key === \"string\" && action.key.trim().length > 0) {",
      "        const label = typeof action.label === \"object\" && action.label !== null",
      "          ? (action.label.nl ?? action.label.en ?? action.key)",
      "          : action.key;",
      "        handles.push({ id: `action:${action.key}`, label });",
      "      }",
      "    }",
      "    if (typeof config.timeout === \"string\" && config.timeout.trim().length > 0) {",
      '      handles.push({ id: "timeout", label: "Time-out" });',
      "    }",
      "    return handles;",
      "  },",
      "  getOutputFields: (_config, handleId) => {",
      "    // awaitAction output fields are empty — form data comes from formDefinition nodes",
      "    return [];",
      "  },",
      `};`,
      "",
    ].join("\n");
  }


  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    `import { ${iconName} } from "lucide-react";`,
    'import type { WorkflowNodeDefinition } from "../../../shared/types";',
    ...(action === "list"
      ? [
          "import {",
          "  buildGeneratedEntityListOutputHandles,",
          '} from "../../shared/error-routes";',
          "import {",
          "  getGeneratedEntityListOutputFieldsForHandle,",
          '} from "../../shared/output-parameters";',
        ]
      : [
          "import {",
          "  buildGeneratedEntityOutputHandles,",
          '} from "../../shared/error-routes";',
        ]),
    `import {`,
    ...sharedImport.map((item) => `  ${item},`),
    '} from "./shared";',
    "",
    `export const ${definitionName}: WorkflowNodeDefinition = {`,
    `  type: ${JSON.stringify(nodeType)},`,
    `  category: ${constPrefix}CategoryLabel,`,
    `  label: ${JSON.stringify(actionLabel.nl)},`,
    `  description: ${JSON.stringify(actionDescription.nl)},`,
    `  icon: ${iconName},`,
    `  configFields: ${configFieldsWithErrorRoutesSource},`,
    `  defaultConfig: ${defaultConfigSource},`,
    `  getOutputHandles: (config) => ${
      action === "list"
        ? "buildGeneratedEntityListOutputHandles(config, [])"
        : "buildGeneratedEntityOutputHandles(config, [])"
    },`,
    `  getOutputFields: (_config, handleId) => ${
      action === "list"
        ? `getGeneratedEntityListOutputFieldsForHandle(${outputFieldsSource}, handleId)`
        : outputFieldsSource
    },`,
    `};`,
    "",
  ].join("\n");
}
