// @ts-nocheck
// SPDX-License-Identifier: BUSL-1.1
import { createHash } from "node:crypto";
import type { DesignerDetailRegistryEntry, DesignerLazyRegistryEntry, RendererEntityFieldSuggestionEntry, WorkflowAction } from "./types.js";
import { ACTION_FILE_NAMES } from "./types.js";
import { formatJson } from "./utils.js";

export function buildEntityIndexSource(input: {
  constName: string;
  definitionNames: string[];
  actions: WorkflowAction[];
}) {
  const { constName, definitionNames, actions } = input;

  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    'import type { WorkflowNodeDefinition } from "../../../shared/types";',
    ...actions.map((action, index) => {
      const fileName = ACTION_FILE_NAMES[action];
      return `import { ${definitionNames[index]} } from "./${fileName}";`;
    }),
    "",
    `export const ${constName}: WorkflowNodeDefinition[] = [`,
    ...definitionNames.map((name) => `  ${name},`),
    "];",
    "",
  ].join("\n");
}

export function buildRootIndexSource(entries: Array<{ constName: string; importPath: string }>) {
  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    'import type { WorkflowNodeDefinition } from "../shared/types";',
    ...entries.map(
      (entry) => `import { ${entry.constName} } from "${entry.importPath}";`,
    ),
    "",
    "export const generatedWorkflowNodeDefinitions: WorkflowNodeDefinition[] = [",
    ...entries.map((entry) => `  ...${entry.constName},`),
    "];",
    "",
  ].join("\n");
}

export function buildDesignerLazyRegistrySource(entries: DesignerLazyRegistryEntry[]) {
  const paletteEntries = entries.map(
    ({ type, action, label, description, category, defaultConfig }) => ({
      type,
      action,
      label,
      description,
      category,
      defaultConfig,
    }),
  );

  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    "export type GeneratedWorkflowNodePaletteEntry = {",
    "  type: `entity.${string}`;",
    '  action: "create" | "getOne" | "list" | "update" | "delete" | "wait" | "awaitAction";',
    "  label: string;",
    "  description: string;",
    "  category: string;",
    "  defaultConfig: Record<string, unknown>;",
    "};",
    "",
    `export const generatedWorkflowNodePaletteEntries = JSON.parse(${JSON.stringify(formatJson(
      paletteEntries,
    ))}) as GeneratedWorkflowNodePaletteEntry[];`,
    "",
  ].join("\n");
}

export function buildDesignerPaletteRegistrySource(entries: DesignerLazyRegistryEntry[]) {
  return `${formatJson(
    entries.map(({ type, action, label, description, category, defaultConfig }) => ({
      type,
      action,
      label,
      description,
      category,
      defaultConfig,
    })),
  )}\n`;
}

export function buildDesignerDetailRegistrySource(entries: DesignerDetailRegistryEntry[]) {
  return `${formatJson(entries)}\n`;
}

export function buildDesignerDetailRegistryShimSource(entries: DesignerDetailRegistryEntry[]) {
  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    'import type { Field } from "@/generated/compiler/field-contract";',
    "",
    "export type GeneratedWorkflowNodeDetailRegistryEntry = {",
    "  type: `entity.${string}`;",
    "  action: \"create\" | \"getOne\" | \"list\" | \"update\" | \"delete\" | \"wait\" | \"awaitAction\";",
    "  configFields: Field[];",
    "  defaultOutputFields: Field[];",
    "};",
    "",
    "// Keep the payload in a JSON.parse string so TypeScript does not infer a",
    "// multi-megabyte literal type during `tsc --noEmit`.",
    `export const generatedWorkflowNodeDetailEntries = JSON.parse(${JSON.stringify(formatJson(
      entries,
    ))}) as GeneratedWorkflowNodeDetailRegistryEntry[];`,
    "",
  ].join("\n");
}

// Seed payload consumed by the Postgres seed step
// (apps/api/src/db/seeds/global/entity-field-suggestions.ts → platform.entity_field_suggestions).
// One entry per entity (deduped by PascalCase name, matching the .ts Record key).
// The checksum is the sha256 of the serialized entries so the seed step can
// checksum-skip idempotently and the Redis cache key stays stable across runs
// with identical output. Mirrors buildEntityTriggerRegistrySeedJson.
export function buildEntityFieldSuggestionsSeedJson(
  entries: RendererEntityFieldSuggestionEntry[],
): string {
  const seenEntities = new Set<string>();
  const uniqueEntries = entries.filter((entry) => {
    if (seenEntities.has(entry.entity)) return false;
    seenEntities.add(entry.entity);
    return true;
  });
  const serializedEntries = JSON.stringify(uniqueEntries);
  const checksum = createHash("sha256").update(serializedEntries).digest("hex");
  return `${JSON.stringify({ checksum, entries: uniqueEntries })}\n`;
}
