// @ts-nocheck
import { createHash } from "node:crypto";
import type { DesignerDetailRegistryEntry, DesignerLazyRegistryEntry, RuntimeRegistryEntry } from "./types.js";

// Joins the palette (lazy) and detail registry arrays by `type` into the
// entity catalog seed payload consumed by the Postgres seed step
// (apps/api/src/db/seeds/global/workflow-node-catalog.ts, catalog='entity').
// label/description come from the palette entry; configFields/defaultOutputFields
// come from the detail entry. The checksum is the sha256 of the serialized
// joined entries so the seed step can checksum-skip idempotently.
export function buildEntityCatalogSeedJson(
  lazyEntries: DesignerLazyRegistryEntry[],
  detailEntries: DesignerDetailRegistryEntry[],
) {
  const detailByType = new Map<string, DesignerDetailRegistryEntry>();
  for (const detail of detailEntries) detailByType.set(detail.type, detail);

  const entries = lazyEntries.map((lazy) => {
    const detail = detailByType.get(lazy.type);
    return {
      nodeType: lazy.type,
      action: lazy.action,
      category: lazy.category,
      label: lazy.label,
      description: lazy.description,
      defaultConfig: lazy.defaultConfig,
      configFields: detail?.configFields ?? [],
      defaultOutputFields: detail?.defaultOutputFields ?? [],
    };
  });

  const serializedEntries = JSON.stringify(entries);
  const checksum = createHash("sha256").update(serializedEntries).digest("hex");
  return `${JSON.stringify({ checksum, catalog: "entity", entries })}\n`;
}

export function buildWorkflowRuntimeRegistryJson(entries: RuntimeRegistryEntry[]) {
  // Compact JSON keeps the artifact under GitHub's 100MB blob limit; the
  // designer/runtime consumers parse JSON and do not need pretty-printing.
  return `${JSON.stringify(entries)}\n`;
}

// The API bridge registration (generated-entity-bridges.ts) only needs a tiny
// routing index — type/module/entity/entityKey/action. The heavy Field[]
// payloads in the full registry are consumed by the web designer, not the API.
// Emitting only the index keeps the API artifact ~KB instead of ~76MB, so
// `tsc` no longer parses a multi-megabyte JSON import on every API typecheck.
export function buildWorkflowBridgeIndexJson(entries: RuntimeRegistryEntry[]) {
  const index = entries.map(({ type, module, entity, entityKey, action }) => ({
    type,
    module,
    entity,
    entityKey,
    action,
  }));
  return `${JSON.stringify(index)}\n`;
}

export function buildWorkflowRuntimeRegistryTypesSource(entries: RuntimeRegistryEntry[]) {
  const uniqueTypes = [...new Set(entries.map((entry) => entry.type))].sort();
  const nodeTypeAlias =
    uniqueTypes.length === 0
      ? ["export type GeneratedEntityWorkflowNodeType = never;"]
      : [
          "export type GeneratedEntityWorkflowNodeType =",
          ...uniqueTypes.map((type, index) => {
            const suffix = index === uniqueTypes.length - 1 ? ";" : "";
            return `  | ${JSON.stringify(type)}${suffix}`;
          }),
        ];

  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    'import type { Field } from "../contract/node-field-contract";',
    "",
    'export type GeneratedWorkflowEntityAction = "create" | "getOne" | "list" | "update" | "delete" | "wait" | "awaitAction";',
    "",
    "export type GeneratedEntityWorkflowNodeDefinition = {",
    "  type: `entity.${string}`;",
    "  module: string;",
    "  entity: string;",
    "  entityKey: string;",
    "  action: GeneratedWorkflowEntityAction;",
    "  label: string;",
    "  description: string;",
    "  category: string;",
    "  readableFields: Field[];",
    "  writableFields: Field[];",
    "  recordIdField: Field;",
    "  listOutputFields: Field[];",
    "  deleteOutputFields: Field[];",
    "  errorOutputFields: Field[];",
    "  supportedErrorRoutes: Array<{",
    "    id: string;",
    "    handleId: string;",
    "    label: string;",
    "    description: string;",
    "    matchCodes: string[];",
    "    matchStatusCodes: number[];",
    "  }>;",
    "  defaultConfig: Record<string, unknown>;",
    "  graphql: {",
    "    singleQuery: string;",
    "    listQuery: string;",
    "    createMutation: string;",
    "    updateMutation: string;",
    "    deleteMutation: string;",
    "  };",
    "};",
    "",
    "// Large registry payload is emitted as entity-workflow-nodes.generated.json",
    "// (same directory) so Git and TypeScript are not asked to parse megabyte literals.",
    ...nodeTypeAlias,
    "",
  ].join("\n");
}
