// @ts-nocheck
// SPDX-License-Identifier: BUSL-1.1
import type { Field } from "../../../../../packages/compiler/src/authoring/types.js";
import { formatJson, makeFieldOptional, toOutputField } from "./utils.js";

export function buildSharedSource(input: {
  constPrefix: string;
  entityLabels: { en: string; nl: string };
  readableFields: Field[];
  writableFields: Field[];
  recordIdField: Field;
  listOutputFields: Field[];
  deleteOutputFields: Field[];
  waitOutputFields: Field[];
  errorOutputFields: Field[];
  waitEventTypeField: Field;
  waitConditionField: Field;
  waitTimeoutField: Field;
  categoryLabel: string;
}) {
  const {
    constPrefix,
    entityLabels,
    readableFields,
    writableFields,
    recordIdField,
    listOutputFields,
    deleteOutputFields,
    waitOutputFields,
    errorOutputFields,
    waitEventTypeField,
    waitConditionField,
    waitTimeoutField,
    categoryLabel,
  } = input;

  return [
    "// Generated by OpenShapeForge Service Compiler.",
    "// Do not edit manually.",
    "",
    'import type { Field } from "@/generated/compiler/field-contract";',
    "",
    `export const ${constPrefix}CategoryLabel = ${JSON.stringify(categoryLabel)};`,
    `export const ${constPrefix}EntityLabels = ${formatJson(entityLabels)} as const;`,
    "",
    `export const ${constPrefix}ReadableFields: Field[] = ${formatJson(readableFields.map(toOutputField))};`,
    "",
    `export const ${constPrefix}WritableFields: Field[] = ${formatJson(writableFields)};`,
    "",
    `export const ${constPrefix}WritableFieldsOptional: Field[] = ${formatJson(writableFields.map(makeFieldOptional))};`,
    "",
    `export const ${constPrefix}RecordIdField: Field = ${formatJson(recordIdField)};`,
    "",
    `export const ${constPrefix}ListOutputFields: Field[] = ${formatJson(listOutputFields)};`,
    "",
    `export const ${constPrefix}DeleteOutputFields: Field[] = ${formatJson(deleteOutputFields)};`,
    "",
    `export const ${constPrefix}WaitOutputFields: Field[] = ${formatJson(waitOutputFields)};`,
    "",
    `export const ${constPrefix}ErrorOutputFields: Field[] = ${formatJson(errorOutputFields)};`,
    "",
    `export const ${constPrefix}WaitEventTypeField: Field = ${formatJson(waitEventTypeField)};`,
    "",
    `export const ${constPrefix}WaitConditionField: Field = ${formatJson(waitConditionField)};`,
    "",
    `export const ${constPrefix}WaitTimeoutField: Field = ${formatJson(waitTimeoutField)};`,
    "",
  ].join("\n");
}
