// SPDX-License-Identifier: BUSL-1.1
import { generatedCrudError } from "./catalog.js";
import { fieldNameForColumn } from "./columns.js";
import type { GeneratedCrudColumn, GeneratedCrudTable } from "./types.js";

const MAX_SUFFIX_ATTEMPTS = 10_000;

export function derivedOnCreateColumn(table: GeneratedCrudTable): GeneratedCrudColumn | undefined {
  const columns = table.columns.filter((column) => column.deriveOnCreate);
  if (columns.length > 1) {
    throw generatedCrudError(
      "Generated CRUD derivation metadata contains more than one create-time derived column.",
      "INTERNAL_SERVER_ERROR",
    );
  }
  return columns[0];
}

export function assertNoDerivedOnCreateValues(
  table: GeneratedCrudTable,
  input: Record<string, unknown>,
): void {
  const column = derivedOnCreateColumn(table);
  if (!column) return;
  const field = fieldNameForColumn(column);
  if (
    Object.prototype.hasOwnProperty.call(input, field) ||
    Object.prototype.hasOwnProperty.call(input, column.name)
  ) {
    throw generatedCrudError(
      `"${field}" is generated by the server when this entity is created and cannot be supplied.`,
      "BAD_USER_INPUT",
    );
  }
}

function slugBase(value: string): string {
  const slug = value
    .normalize("NFKD")
    .replace(/\p{Mark}+/gu, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return slug || "item";
}

export function derivedSlugCandidate(
  value: unknown,
  attempt: number,
  maxLength?: number,
): string {
  if (typeof value !== "string" || value.trim().length === 0) {
    throw generatedCrudError(
      "The source of a create-time derived identifier must be a non-empty string.",
      "BAD_USER_INPUT",
    );
  }
  if (!Number.isSafeInteger(attempt) || attempt < 1 || attempt > MAX_SUFFIX_ATTEMPTS) {
    throw generatedCrudError(
      "Generated CRUD could not allocate a unique derived identifier.",
      "INTERNAL_SERVER_ERROR",
    );
  }
  const suffix = attempt === 1 ? "" : `-${attempt}`;
  if (maxLength !== undefined && maxLength <= suffix.length) {
    throw generatedCrudError(
      "The authored maximum length is too small for a suffixed derived identifier.",
      "INTERNAL_SERVER_ERROR",
    );
  }
  const base = slugBase(value);
  const available = maxLength === undefined ? base.length : maxLength - suffix.length;
  const fitted = base.slice(0, available).replace(/-+$/g, "") || "item".slice(0, available);
  return `${fitted}${suffix}`;
}

export function maxDerivedIdentifierAttempts(): number {
  return MAX_SUFFIX_ATTEMPTS;
}
