// SPDX-License-Identifier: BUSL-1.1
import { describe, expect, test } from "bun:test";
import {
  assertNoDerivedOnCreateValues,
  derivedSlugCandidate,
} from "./derive-on-create.js";
import { isWritableColumn, normalizeWritableValues } from "./write-policy.js";
import type { GeneratedCrudColumn, GeneratedCrudTable } from "./types.js";

const key: GeneratedCrudColumn = {
  name: "key",
  sourceField: "key",
  type: "text",
  required: true,
  primaryKey: false,
  generated: null,
  deriveOnCreate: {
    sourceField: "name",
    sourceColumn: "name",
    transform: "slug",
    onConflict: "suffix",
    conflictColumns: ["tenant_id", "key"],
    maxLength: 12,
  },
};
const name: GeneratedCrudColumn = {
  name: "name",
  sourceField: "name",
  type: "text",
  required: true,
  primaryKey: false,
  generated: null,
};
const table = {
  name: "erp.templates",
  schema: "erp",
  table: "templates",
  tenantScoped: true,
  domainInternal: false,
  generatedCrudEligible: true,
  primaryKey: "id",
  columns: [key, name],
} satisfies GeneratedCrudTable;

describe("create-time derived identifiers", () => {
  test("normalizes stable ASCII slugs and reserves room for collision suffixes", () => {
    expect(derivedSlugCandidate("  Café & Crème  ", 1, 100)).toBe("cafe-creme");
    expect(derivedSlugCandidate("A very long template", 2, 12)).toBe("a-very-lon-2");
    expect(derivedSlugCandidate("東京", 1, 100)).toBe("item");
  });

  test("keeps the derived column server-owned on create and update", () => {
    expect(isWritableColumn(key, "create")).toBe(false);
    expect(isWritableColumn(key, "update")).toBe(false);
    expect([...normalizeWritableValues(table, { name: "Offer" }, "create").values()]).toEqual(["Offer"]);
    expect(() => assertNoDerivedOnCreateValues(table, { key: "caller-choice" })).toThrow(/generated by the server/);
    expect(() => normalizeWritableValues(table, { key: "caller-choice", name: "Offer" }, "create")).toThrow(/generated by the server/);
  });
});
