// SPDX-License-Identifier: BUSL-1.1
import { createHash } from "node:crypto";
import { renderOpenApiSpec } from "./generate-openapi.js";
import type {
  ColumnDefinition,
  GeneratedArtifact,
  PlatformSchemaManifest,
  RowScopePolicy,
  ScalarType,
  TableDefinition,
} from "./schema.js";

type GroupExpand = NonNullable<RowScopePolicy["group"]>["expand"];

const defaultSource = "packages/compiler/config/platform-schema.yaml";

export type GenerateArtifactsOptions = {
  source?: string;
};

function sqlGeneratedHeader(source: string): string {
  return [
    "-- Generated by OpenShapeForge Service Compiler. Do not edit by hand.",
    `-- Source: ${source}`,
  ].join("\n");
}

function tsGeneratedHeader(source: string): string {
  return [
    "// Generated by OpenShapeForge Service Compiler. Do not edit by hand.",
    `// Source: ${source}`,
  ].join("\n");
}

function quoteIdent(value: string): string {
  // Double any embedded double-quote so a hostile or malformed identifier
  // cannot break out of the quoted-identifier syntax (mirrors quoteSqlString's
  // single-quote doubling). This is the belt to storage.ts's suspenders: the
  // authoring-layer allowlist (validateColumnIdentifier) is the primary guard,
  // but escaping here keeps every emitted identifier well-formed regardless of
  // caller.
  return `"${value.replace(/"/g, '""')}"`;
}

function quoteSqlString(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function tableIdent(table: TableDefinition): string {
  return `${quoteIdent(table.schema)}.${quoteIdent(table.name)}`;
}

function stableIdentifier(value: string): string {
  if (value.length <= 63) {
    return value;
  }
  const hash = createHash("sha256").update(value).digest("hex").slice(0, 8);
  return `${value.slice(0, 54)}_${hash}`;
}

function sqlType(type: ScalarType): string {
  switch (type) {
    case "uuid":
      return "uuid";
    case "text":
      return "text";
    case "boolean":
      return "boolean";
    case "integer":
      return "integer";
    case "bigint":
      return "bigint";
    case "numeric":
      return "numeric";
    case "date":
      return "date";
    case "timestamptz":
      return "timestamptz";
    case "jsonb":
      return "jsonb";
  }
}

function tsType(type: ScalarType): string {
  switch (type) {
    case "uuid":
    case "text":
      return "string";
    case "boolean":
      return "boolean";
    case "integer":
      return "number";
    case "bigint":
      return "string";
    case "numeric":
      return "Numeric";
    case "date":
      return "DateOnly";
    case "timestamptz":
      return "Timestamp";
    case "jsonb":
      return "Json";
  }
}

function generatedTsType(column: ColumnDefinition): string {
  if (column.type === "timestamptz") {
    return "GeneratedTimestamp";
  }

  return `Generated<${tsType(column.type)}>`;
}

function pascalCase(value: string): string {
  return value
    .split(/[_-]/)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}

function renderColumnSql(column: ColumnDefinition): string {
  const parts = [quoteIdent(column.name), sqlType(column.type)];

  if (column.generated === "identity") {
    parts.push("GENERATED BY DEFAULT AS IDENTITY");
  }
  if (column.primaryKey) {
    parts.push("PRIMARY KEY");
  }
  if (column.required || column.primaryKey) {
    parts.push("NOT NULL");
  }
  if (column.default) {
    parts.push("DEFAULT", column.default);
  }

  return `  ${parts.join(" ")}`;
}

function columnNames(table: TableDefinition): Set<string> {
  return new Set(table.columns.map((column) => column.name));
}

/**
 * Map a group-axis `expand` mode to the SQL session-groups reader function.
 * Descendants is the default (and the historical `app.current_groups()`), so
 * an undefined/descendants mode keeps byte-identical output for existing
 * descendant-mode policies.
 */
function groupFunctionForExpand(expand: GroupExpand): string {
  switch (expand) {
    case "exact":
      return "app.current_groups_exact()";
    case "ancestors":
      return "app.current_groups_ancestors()";
    case "descendants":
    case undefined:
      return "app.current_groups()";
    default: {
      // Exhaustiveness guard: a new expand mode must add its function here.
      const never: never = expand;
      throw new Error(`Unknown group expand mode "${String(never)}".`);
    }
  }
}

function renderRowScopePredicate(table: TableDefinition): string | undefined {
  const scope = table.rowScope;
  if (!scope) return undefined;

  const present = columnNames(table);
  const branches: string[] = [];

  if (scope.bypassRoles && scope.bypassRoles.length > 0) {
    branches.push("app.has_scope('tenant')");
  }
  if (scope.group) {
    if (!present.has(scope.group.column)) {
      throw new Error(
        `Table ${table.schema}.${table.name} declares rowScope.group.column "${scope.group.column}" but the column is not defined. ` +
          `Add the column to the entity or remove the group axis from rowScope.`,
      );
    }
    // Select the session-groups reader by expand mode. Each is a uuid[] GUC
    // reader set once per session in applyDbSession (session.ts):
    //   descendants (default) → app.current_groups()           (app.user_groups)
    //   exact                 → app.current_groups_exact()      (app.user_groups_exact)
    //   ancestors             → app.current_groups_ancestors()  (app.user_groups_ancestors)
    // The policy stays a flat `= ANY(<fn>())` — expansion is precomputed at
    // session setup, so the hot policy path never joins the closure.
    branches.push(
      `${quoteIdent(scope.group.column)} = ANY (${groupFunctionForExpand(scope.group.expand)})`,
    );
  }
  for (const userColumn of scope.userColumns ?? []) {
    if (!present.has(userColumn)) {
      throw new Error(
        `Table ${table.schema}.${table.name} declares rowScope.userColumns "${userColumn}" but the column is not defined. ` +
          `Add the column to the entity or remove it from rowScope.userColumns.`,
      );
    }
    branches.push(`${quoteIdent(userColumn)} = app.current_user_id()`);
  }
  // `empty: public` — each listed column emits an extra "IS NULL" OR-branch so
  // that rows whose owner/group column is NULL stay visible tenant-wide.
  // Validated for presence exactly like the group/user axes.
  for (const nullVisibleColumn of scope.nullVisibleColumns ?? []) {
    if (!present.has(nullVisibleColumn)) {
      throw new Error(
        `Table ${table.schema}.${table.name} declares rowScope.nullVisibleColumns "${nullVisibleColumn}" but the column is not defined. ` +
          `Add the column to the entity or remove it from rowScope.nullVisibleColumns.`,
      );
    }
    branches.push(`${quoteIdent(nullVisibleColumn)} IS NULL`);
  }

  // Tenant predicate is always required when rowScope is set.
  const tenant = "tenant_id = app.current_tenant()";

  if (branches.length === 0) {
    // Caller declared rowScope with no group/user axes — degenerate case;
    // behave the same as plain tenant scoping.
    return `app.bypass_rls() OR (${tenant})`;
  }

  return `app.bypass_rls() OR (${tenant} AND (${branches.join(" OR ")}))`;
}

function deriveRowScopeIndexes(table: TableDefinition): Array<{
  name: string;
  columns: string[];
  where?: string;
}> {
  const scope = table.rowScope;
  if (!scope) return [];

  const indexes: Array<{ name: string; columns: string[]; where?: string }> = [];

  if (scope.group) {
    indexes.push({
      name: `${table.name}_tenant_${scope.group.column}_idx`,
      columns: ["tenant_id", scope.group.column],
    });
  }
  for (const userColumn of scope.userColumns ?? []) {
    indexes.push({
      name: `${table.name}_tenant_${userColumn}_idx`,
      columns: ["tenant_id", userColumn],
      where: `${quoteIdent(userColumn)} IS NOT NULL`,
    });
  }

  return indexes;
}

function renderIndexSql(
  table: TableDefinition,
  index: { name: string; columns: string[]; unique?: boolean; where?: string },
): string {
  const cols = index.columns.map(quoteIdent).join(", ");
  const keyword = index.unique ? "CREATE UNIQUE INDEX" : "CREATE INDEX";
  // Stabilize over-length names so two distinct index names sharing their
  // first 63 bytes do not collapse into one after Postgres truncation (which
  // would make `CREATE INDEX IF NOT EXISTS` silently skip the second).
  const indexName = stableIdentifier(index.name);
  const head = `${keyword} IF NOT EXISTS ${quoteIdent(indexName)} ON ${tableIdent(table)} (${cols})`;
  return index.where ? `${head} WHERE ${index.where};` : `${head};`;
}

function renderTableSql(table: TableDefinition): string {
  const lines = [
    `CREATE SCHEMA IF NOT EXISTS ${quoteIdent(table.schema)};`,
    "",
    `CREATE TABLE IF NOT EXISTS ${tableIdent(table)} (`,
    table.columns.map(renderColumnSql).join(",\n"),
    ");",
  ];

  if (table.tenantScoped) {
    const rowScopePredicate = renderRowScopePredicate(table);
    if (rowScopePredicate) {
      const policyName = quoteIdent(`${table.name}_row_scope`);
      lines.push(
        "",
        `ALTER TABLE ${tableIdent(table)} ENABLE ROW LEVEL SECURITY;`,
        `ALTER TABLE ${tableIdent(table)} FORCE ROW LEVEL SECURITY;`,
        `DROP POLICY IF EXISTS ${policyName} ON ${tableIdent(table)};`,
        `CREATE POLICY ${policyName} ON ${tableIdent(table)}`,
        `  USING (${rowScopePredicate})`,
        `  WITH CHECK (${rowScopePredicate});`,
      );
    } else {
      const policyName = quoteIdent(`${table.name}_tenant_isolation`);
      const tenantExpression = "tenant_id = app.current_tenant()";
      lines.push(
        "",
        `ALTER TABLE ${tableIdent(table)} ENABLE ROW LEVEL SECURITY;`,
        `ALTER TABLE ${tableIdent(table)} FORCE ROW LEVEL SECURITY;`,
        `DROP POLICY IF EXISTS ${policyName} ON ${tableIdent(table)};`,
        `CREATE POLICY ${policyName} ON ${tableIdent(table)}`,
        `  USING (${tenantExpression})`,
        `  WITH CHECK (${tenantExpression});`,
      );
    }
  }

  for (const index of deriveRowScopeIndexes(table)) {
    lines.push("", renderIndexSql(table, index));
  }
  for (const index of table.indexes ?? []) {
    lines.push("", renderIndexSql(table, index));
  }

  return lines.join("\n");
}

function renderColumnForeignKeySql(table: TableDefinition, column: ColumnDefinition): string | undefined {
  if (!column.references) {
    return undefined;
  }

  const constraintName = stableIdentifier(`${table.name}_${column.name}_fkey`);
  const reference = column.references;
  const onDelete = reference.onDelete ? ` ON DELETE ${reference.onDelete}` : "";

  return [
    "DO $openshapeforge_fk$",
    "BEGIN",
    "  IF NOT EXISTS (",
    "    SELECT 1",
    "    FROM pg_constraint c",
    "    JOIN pg_class t ON t.oid = c.conrelid",
    "    JOIN pg_namespace n ON n.oid = t.relnamespace",
    `    WHERE c.conname = ${quoteSqlString(constraintName)}`,
    `      AND n.nspname = ${quoteSqlString(table.schema)}`,
    `      AND t.relname = ${quoteSqlString(table.name)}`,
    "  ) THEN",
    `    ALTER TABLE ${tableIdent(table)}`,
    `      ADD CONSTRAINT ${quoteIdent(constraintName)} FOREIGN KEY (${quoteIdent(column.name)})`,
    `      REFERENCES ${quoteIdent(reference.schema)}.${quoteIdent(reference.table)}(${quoteIdent(reference.column)})${onDelete};`,
    "  END IF;",
    "END",
    "$openshapeforge_fk$;",
  ].join("\n");
}

function renderForeignKeySql(manifest: PlatformSchemaManifest): string {
  return manifest.tables
    .flatMap((table) =>
      table.columns
        .map((column) => renderColumnForeignKeySql(table, column))
        .filter((sql): sql is string => sql !== undefined),
    )
    .join("\n\n");
}

function renderKyselyTypes(manifest: PlatformSchemaManifest, source: string): string {
  const interfaces = manifest.tables.map((table) => {
    const name = `${pascalCase(table.schema)}${pascalCase(table.name)}Table`;
    const columns = table.columns
      .map((column) => {
        const nullable = column.required || column.primaryKey ? "" : " | null";
        const generated =
          column.default || column.generated === "identity"
            ? generatedTsType(column)
            : `${tsType(column.type)}${nullable}`;
        return `  ${column.name}: ${generated};`;
      })
      .join("\n");
    return `export interface ${name} {\n${columns}\n}`;
  });

  const dbFields = manifest.tables
    .map((table) => {
      const name = `${pascalCase(table.schema)}${pascalCase(table.name)}Table`;
      return `  "${table.schema}.${table.name}": ${name};`;
    })
    .join("\n");

  return `${tsGeneratedHeader(source)}

import type { ColumnType, Generated } from "kysely";

export type Json =
  | null
  | boolean
  | number
  | string
  | Json[]
  | { [key: string]: Json };

export type Timestamp = ColumnType<string, string | Date, string | Date>;
export type GeneratedTimestamp = ColumnType<string, string | Date | undefined, string | Date>;
export type DateOnly = ColumnType<string, string | Date, string | Date>;
export type Numeric = ColumnType<string, string | number, string | number>;

${interfaces.join("\n\n")}

export interface DB {
${dbFields}
}
`;
}

function renderManifestJson(manifest: PlatformSchemaManifest, source: string): string {
  const checksum = createHash("sha256")
    .update(JSON.stringify(manifest))
    .digest("hex");
  const tables = manifest.tables.map((table) => ({
    name: `${table.schema}.${table.name}`,
    schema: table.schema,
    table: table.name,
    tenantScoped: table.tenantScoped,
    domainInternal: table.domainInternal === true,
    // Fail-closed: a table is CRUD-exposed only when it opts in explicitly
    // with `generatedCrud: true`. A table that omits the flag (or is
    // domain-internal) is not exposed, so a forgotten opt-out on a new
    // sensitive table cannot silently advertise it as CRUD-generated.
    generatedCrud: table.generatedCrud === true && table.domainInternal !== true,
    primaryKey:
      table.columns.find((column) => column.primaryKey)?.name ?? null,
    columns: table.columns.map((column) => ({
      name: column.name,
      type: column.type,
      required: column.required === true || column.primaryKey === true,
      primaryKey: column.primaryKey === true,
      generated: column.generated ?? null,
      // Verbatim SQL default so the roll-forward migrator can detect default
      // drift (a changed default is otherwise invisible: it does not alter
      // information_schema.data_type/nullability/identity).
      ...(column.default === undefined ? {} : { default: column.default }),
      ...(column.sourceField === undefined ? {} : { sourceField: column.sourceField }),
    })),
    ...(table.retention === undefined ? {} : { retention: table.retention }),
    ...(table.source === undefined ? {} : { source: table.source }),
  }));
  const generatedEntities = tables
    .filter((table) =>
      table.generatedCrud &&
      !table.domainInternal &&
      table.primaryKey &&
      table.source?.graphql
    )
    .map((table) => ({
      slug: table.source?.authoringEntitySlug ?? table.name,
      table: table.name,
      tenantScoped: table.tenantScoped,
      primaryKey: table.primaryKey,
      graphql: {
        typeName: table.source!.graphql!.typeName,
        singleQueryName: table.source!.graphql!.singleQueryName,
        listQueryName: table.source!.graphql!.listQueryName,
        createMutationName: table.source!.graphql!.createMutationName,
        updateMutationName: table.source!.graphql!.updateMutationName,
        deleteMutationName: table.source!.graphql!.deleteMutationName,
      },
      ...(table.source?.rest === undefined ? {} : { rest: table.source.rest }),
      fields: table.columns.map((column) => ({
        field: column.sourceField ?? column.name.replace(/_([a-z0-9])/g, (_match, char: string) => char.toUpperCase()),
        column: column.name,
        type: column.type,
        required: column.required,
        primaryKey: column.primaryKey,
      })),
    }))
    .sort((a, b) => a.slug.localeCompare(b.slug));

  return `${JSON.stringify(
    {
      generatedBy: "@openshapeforge/compiler",
      source,
      checksum,
      capabilities: {
        generatedEntities,
      },
      tables,
    },
    null,
    2,
  )}\n`;
}

export function generateArtifacts(
  manifest: PlatformSchemaManifest,
  options: GenerateArtifactsOptions = {},
): GeneratedArtifact[] {
  const source = options.source ?? defaultSource;
  const sql = `${sqlGeneratedHeader(source)}

CREATE EXTENSION IF NOT EXISTS pgcrypto;

${manifest.tables.map(renderTableSql).join("\n\n")}

-- OpenShapeForge generated foreign keys: keep after table creation for cyclic catalog relationships.
${renderForeignKeySql(manifest)}
`;

  return [
    {
      path: "apps/api/src/generated/db/schema.sql",
      contents: sql,
    },
    {
      path: "apps/api/src/generated/db/types.ts",
      contents: renderKyselyTypes(manifest, source),
    },
    {
      path: "apps/api/src/generated/db/manifest.json",
      contents: renderManifestJson(manifest, source),
    },
    {
      path: "apps/api/src/generated/rest/openapi.json",
      contents: renderOpenApiSpec(manifest, source),
    },
  ];
}
