// SPDX-License-Identifier: BUSL-1.1
import { expect, test } from "bun:test";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import YAML from "yaml";
import { collectAllArtifacts } from "./index.js";

test("committed REST onboarding reaches the generated OpenAPI artifact", async () => {
  const repoRoot = mkdtempSync(join(tmpdir(), "openshapeforge-rest-onboarding-"));
  try {
    writeFileSync(
      join(repoRoot, "authoring.config.yaml"),
      YAML.stringify({
        layers: ["packages/compiler/config/authoring"],
        restApi: {
          title: "Example Product API",
          description: "Authenticate first, then follow the integration workflow.",
          externalDocs: {
            description: "Developer guide",
            url: "https://example.com/developers",
          },
        },
      }),
      "utf8",
    );

    const artifacts = await collectAllArtifacts(repoRoot);
    const openApi = JSON.parse(
      artifacts.groups.db.find(
        (artifact) => artifact.path === "apps/api/src/generated/rest/openapi.json",
      )!.contents,
    ) as {
      info: { title: string; version: string; description: string };
      externalDocs: { description: string; url: string };
    };

    expect(openApi.info.title).toBe("Example Product API");
    expect(openApi.info.version).toBe("1");
    expect(openApi.info.description).toStartWith(
      "Authenticate first, then follow the integration workflow.",
    );
    expect(openApi.info.description).toContain("Generated by @openshapeforge/compiler");
    expect(openApi.externalDocs).toEqual({
      description: "Developer guide",
      url: "https://example.com/developers",
    });
  } finally {
    rmSync(repoRoot, { recursive: true, force: true });
  }
}, 60_000);
