// SPDX-License-Identifier: BUSL-1.1
import { expect, test } from "bun:test";
import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pruneGeneratedUiShards } from "./prune-generated-ui-shards.js";

test("prunes only retired compiler-authored UI shards and is repeatable", async () => {
  const root = await mkdtemp(join(tmpdir(), "osf-ui-shards-"));
  const directory = "apps/web/src/actions/generated";
  try {
    await mkdir(join(root, directory, "__tests__"), { recursive: true });
    const generated = "// Generated by OpenShapeForge Service Compiler\nexport {};\n";
    await writeFile(join(root, directory, "retired.ts"), generated);
    await writeFile(join(root, directory, "current.ts"), generated);
    await writeFile(join(root, directory, "manual.ts"), "export {};\n");
    await writeFile(join(root, directory, "__tests__/kept.ts"), generated);
    await writeFile(join(root, "outside.ts"), generated);
    await symlink(join(root, "outside.ts"), join(root, directory, "linked.ts"));
    const emitted = new Set([`${directory}/current.ts`]);
    expect(await pruneGeneratedUiShards(root, emitted)).toEqual([`${directory}/retired.ts`]);
    expect(await readFile(join(root, directory, "current.ts"), "utf8")).toBe(generated);
    expect(await readFile(join(root, directory, "manual.ts"), "utf8")).toBe("export {};\n");
    expect(await readFile(join(root, directory, "__tests__/kept.ts"), "utf8")).toBe(generated);
    expect(await readFile(join(root, directory, "linked.ts"), "utf8")).toBe(generated);
    expect(await pruneGeneratedUiShards(root, emitted)).toEqual([]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("does not traverse a symlinked shard directory", async () => {
  const root = await mkdtemp(join(tmpdir(), "osf-ui-shards-"));
  try {
    await mkdir(join(root, "apps/web/src/actions"), { recursive: true });
    await mkdir(join(root, "external"));
    const generated = "// Generated by OpenShapeForge Service Compiler\n";
    await writeFile(join(root, "external/kept.ts"), generated);
    await symlink(join(root, "external"), join(root, "apps/web/src/actions/generated"));
    expect(await pruneGeneratedUiShards(root, new Set())).toEqual([]);
    expect(await readFile(join(root, "external/kept.ts"), "utf8")).toBe(generated);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});
