// SPDX-License-Identifier: BUSL-1.1
import { lstat, readFile, readdir, unlink } from "node:fs/promises";
import { join } from "node:path";

const shardDirectories = [
  "apps/web/src/actions/generated",
  "apps/web/src/compiler/entity-manifests",
] as const;
const compilerHeader = "// Generated by OpenShapeForge Service Compiler\n";

/** Remove retired stock UI shards after a successful compile, never hand-written files. */
export async function pruneGeneratedUiShards(repoRoot: string, emittedPaths: ReadonlySet<string>): Promise<string[]> {
  const removed: string[] = [];
  for (const directory of shardDirectories) {
    const root = join(repoRoot, directory);
    const stat = await lstat(root).catch((error: NodeJS.ErrnoException) => {
      if (error.code === "ENOENT") return undefined;
      throw error;
    });
    if (!stat?.isDirectory() || stat.isSymbolicLink()) continue;
    for (const entry of await readdir(root, { withFileTypes: true })) {
      if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
      const path = `${directory}/${entry.name}`;
      if (emittedPaths.has(path)) continue;
      const target = join(repoRoot, path);
      if (!(await readFile(target, "utf8")).startsWith(compilerHeader)) continue;
      await unlink(target);
      removed.push(path);
    }
  }
  return removed.sort();
}
