// SPDX-License-Identifier: BUSL-1.1
/**
 * Types for stylesheet imports.
 *
 * Next writes an equivalent declaration into `next-env.d.ts`, but that file is
 * generated by a build and gitignored, and `typecheck:web` runs before
 * `build:web` in CI — so on a clean checkout it does not exist yet. Declaring
 * it here means the type gate does not depend on a build having happened.
 */
declare module "*.module.css" {
  const classes: Readonly<Record<string, string>>;
  export default classes;
}

declare module "*.css";
