// SPDX-License-Identifier: BUSL-1.1
"use client";

import type { ComponentType } from "react";
import {
  Activity,
  Archive,
  ArrowLeft,
  ArrowRight,
  AtSign,
  Award,
  BadgeCheck,
  BadgeDollarSign,
  BadgeEuro,
  Banknote,
  BarChart,
  Bell,
  Bookmark,
  BookOpenText,
  BookUser,
  Braces,
  Briefcase,
  Bug,
  Building,
  Building2,
  Calculator,
  Calendar,
  CalendarClock,
  Check,
  CheckSquare,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDollarSign,
  CircleHelp,
  CirclePlus,
  CircleStop,
  CircleX,
  Clipboard,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Clock3,
  Copy,
  CreditCard,
  Database,
  DoorClosed,
  DoorOpen,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  File,
  FileSearch,
  FileStack,
  FileText,
  Filter,
  Flag,
  Folder,
  FolderKanban,
  FolderTree,
  GitBranch,
  Grid3X3,
  Hammer,
  Heart,
  Home,
  IdCard,
  Image,
  Inbox,
  Info,
  Layers,
  Library,
  LifeBuoy,
  Link,
  List,
  ListChecks,
  ListTodo,
  ListTree,
  Loader,
  Lock,
  Mail,
  MapPin,
  MapPinned,
  Merge,
  MessageCircle,
  MessageSquare,
  Minus,
  Package,
  Pencil,
  Phone,
  Play,
  Plus,
  RefreshCw,
  ReceiptText,
  Rows3,
  Save,
  Search,
  Send,
  Settings,
  Shield,
  ShieldCheck,
  Shovel,
  ShoppingCart,
  Split,
  SquarePen,
  Star,
  Tag,
  Timer,
  Trash2,
  TriangleAlert,
  Truck,
  Unlock,
  Upload,
  User,
  Users,
  Vault,
  Waypoints,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
  type LucideProps,
} from "lucide-react";

type IconComponent = ComponentType<LucideProps>;

function toKebabCase(name: string): string {
  return name
    .replace(/([A-Z])/g, (char, _match, offset) => (offset > 0 ? "-" : "") + char.toLowerCase())
    .replace(/([a-z])(\d)/g, "$1-$2")
    .toLowerCase();
}

function normalizeIconName(name: string): string {
  return name.includes("-") ? name.toLowerCase() : toKebabCase(name);
}

const LUCIDE_ICON_REGISTRY = {
  activity: Activity,
  archive: Archive,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "at-sign": AtSign,
  award: Award,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "badge-euro": BadgeEuro,
  banknote: Banknote,
  "bar-chart": BarChart,
  bell: Bell,
  bookmark: Bookmark,
  "book-open-text": BookOpenText,
  "book-user": BookUser,
  braces: Braces,
  briefcase: Briefcase,
  bug: Bug,
  building: Building,
  "building-2": Building2,
  calculator: Calculator,
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  check: Check,
  "check-square": CheckSquare,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-check": CircleCheck,
  "circle-dollar-sign": CircleDollarSign,
  "circle-help": CircleHelp,
  "circle-plus": CirclePlus,
  "circle-stop": CircleStop,
  "circle-x": CircleX,
  clipboard: Clipboard,
  "clipboard-check": ClipboardCheck,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "clock-3": Clock3,
  copy: Copy,
  "credit-card": CreditCard,
  database: Database,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  download: Download,
  "external-link": ExternalLink,
  eye: Eye,
  "eye-off": EyeOff,
  file: File,
  "file-search": FileSearch,
  "file-stack": FileStack,
  "file-text": FileText,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  "folder-kanban": FolderKanban,
  "folder-tree": FolderTree,
  "git-branch": GitBranch,
  grid: Grid3X3,
  "grid-3-x-3": Grid3X3,
  hammer: Hammer,
  heart: Heart,
  home: Home,
  "id-card": IdCard,
  image: Image,
  inbox: Inbox,
  info: Info,
  layers: Layers,
  library: Library,
  "life-buoy": LifeBuoy,
  link: Link,
  list: List,
  "list-checks": ListChecks,
  "list-todo": ListTodo,
  "list-tree": ListTree,
  loader: Loader,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  "map-pinned": MapPinned,
  merge: Merge,
  "message-circle": MessageCircle,
  "message-square": MessageSquare,
  minus: Minus,
  package: Package,
  pencil: Pencil,
  phone: Phone,
  play: Play,
  plus: Plus,
  "refresh-cw": RefreshCw,
  "receipt-text": ReceiptText,
  "rows-3": Rows3,
  save: Save,
  search: Search,
  send: Send,
  settings: Settings,
  shield: Shield,
  "shield-check": ShieldCheck,
  shovel: Shovel,
  "shopping-cart": ShoppingCart,
  split: Split,
  "square-pen": SquarePen,
  star: Star,
  tag: Tag,
  timer: Timer,
  "trash-2": Trash2,
  "triangle-alert": TriangleAlert,
  truck: Truck,
  unlock: Unlock,
  upload: Upload,
  user: User,
  users: Users,
  vault: Vault,
  waypoints: Waypoints,
  webhook: Webhook,
  workflow: Workflow,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<string, IconComponent>;

const LUCIDE_ICON_ALIASES = {
  "address-book": "book-user",
  "address-book-tabs": "book-user",
  buildings: "building-2",
  "git-fork": "git-branch",
  "help-circle": "circle-help",
  "x-circle": "circle-x",
  "check-circle": "circle-check",
  alert: "triangle-alert",
  "alert-triangle": "triangle-alert",
  "dollar-sign": "badge-dollar-sign",
  edit: "pencil",
  grid: "grid-3-x-3",
  // lucide renamed the circle-prefixed icons; the old spelling still ships as a
  // deprecated export and still appears in authored icon names, so both resolve.
  "plus-circle": "circle-plus",
  "stop-circle": "circle-stop",
  screwdriver: "wrench",
  "smiley-melting": "circle-help",
  tray: "inbox",
} satisfies Record<string, keyof typeof LUCIDE_ICON_REGISTRY>;

/**
 * Every name the registry answers to, including aliases.
 *
 * Take this rather than `string` wherever an icon name is authored in code:
 * `resolveLucideIconByName` cannot fail, it falls back to a grey circle, and a
 * grey circle on a canvas node is indistinguishable from a design decision. A
 * typo should stop the build instead.
 */
export type LucideIconName =
  | keyof typeof LUCIDE_ICON_REGISTRY
  | keyof typeof LUCIDE_ICON_ALIASES;

export const AVAILABLE_LUCIDE_ICON_NAMES = Object.keys(LUCIDE_ICON_REGISTRY).sort();

export const POPULAR_LUCIDE_ICON_NAMES = [
  "check",
  "x",
  "plus",
  "minus",
  "pencil",
  "trash-2",
  "save",
  "download",
  "upload",
  "search",
  "settings",
  "user",
  "users",
  "mail",
  "phone",
  "calendar",
  "clock",
  "star",
  "heart",
  "home",
  "file",
  "folder",
  "image",
  "link",
  "eye",
  "eye-off",
  "lock",
  "unlock",
  "triangle-alert",
  "info",
  "circle-help",
  "circle-check",
  "circle-x",
  "arrow-right",
  "arrow-left",
  "chevron-right",
  "chevron-down",
  "external-link",
  "copy",
  "clipboard",
  "refresh-cw",
  "loader",
  "send",
  "bell",
  "tag",
  "filter",
  "list",
  "grid-3-x-3",
  "map-pin",
  "truck",
  "package",
  "shopping-cart",
  "credit-card",
  "badge-dollar-sign",
  "bar-chart",
  "activity",
  "zap",
  "shield",
  "award",
  "flag",
  "bookmark",
] satisfies Array<keyof typeof LUCIDE_ICON_REGISTRY>;

/**
 * Resolving a name that is definitely present always yields a component — the
 * registry falls back to `Circle` rather than failing — so callers holding a
 * name do not have to handle an `undefined` the implementation cannot return.
 */
export function resolveLucideIconByName(name: string): IconComponent;
export function resolveLucideIconByName(name?: string): IconComponent | undefined;
export function resolveLucideIconByName(name?: string): IconComponent | undefined {
  if (!name) return undefined;

  const normalized = normalizeIconName(name);
  const key = LUCIDE_ICON_ALIASES[normalized as keyof typeof LUCIDE_ICON_ALIASES] ?? normalized;

  return LUCIDE_ICON_REGISTRY[key as keyof typeof LUCIDE_ICON_REGISTRY] ?? Circle;
}
