#!/usr/bin/env bun
// SPDX-License-Identifier: BUSL-1.1
/**
 * Functional acceptance for external identity providers (#488), run against a
 * REAL Keycloak — the image built from packages/keycloak-spi — in
 * .github/workflows/docker-keycloak.yml.
 *
 * The unit tests in packages/compiler prove serialisation; the image workflow
 * proves the provider factories load. This closes the gap in between: it takes
 * realms GENERATED by the compiler's Keycloak generator, imports them through
 * Keycloak's admin API, and drives real broker logins over HTTP without a
 * browser (Keycloak's login pages are plain HTML forms).
 *
 * Two realms, both generated:
 *
 *   osf-idp     the "customer's own identity provider" — plays the upstream.
 *               A generated gateway client (`customer-workforce`) is the OIDC
 *               relying party, users alice / bob / carol carry a `tid`
 *               attribute that the gateway client's protocol mapper exposes
 *               as a `tid` claim. A SAML client is added through the admin
 *               API (the authoring contract has no SAML *client* kind; the
 *               upstream is a fixture, the broker realm is what is under test).
 *
 *   osf-broker  the realm under test. A generated gateway client (`gw`) is
 *               what a product would log in through; two generated identity
 *               providers — `customer-workforce` (providerId: oidc) with an
 *               attribute mapper, and `customer-saml` (providerId: saml) with
 *               an attribute mapper — point at osf-idp with host-authored
 *               endpoints. A local user shares bob's e-mail address.
 *
 * What is proven, in order:
 *   1. the generated realm JSON imports unchanged, and the admin API reads the
 *      provider config back exactly as authored;
 *   2. a dedicated OIDC provider logs alice in end-to-end, and the mapper lands
 *      the upstream `tid` claim on the brokered user (visible as `tid` in the
 *      broker's own access token);
 *   3. a repeat login is a plain login (no first-broker-login steps) and keeps
 *      the same subject;
 *   4. an incoming identity whose e-mail matches an EXISTING local account is
 *      NOT linked silently: the flow stops at Keycloak's confirm-link page, no
 *      code is issued, and the local account has no federated identity;
 *   5. the generic SAML provider logs carol in end-to-end with its mapper.
 *
 * Apple is deliberately NOT here: it needs real Apple credentials and a
 * registered domain, so it stays external product evidence (see #488).
 *
 * Environment:
 *   KC_URL           browser-facing base URL (default http://127.0.0.1:8080)
 *   KC_INTERNAL_URL  URL Keycloak uses to reach ITSELF for token/JWKS fetches
 *                    (default KC_URL; differs only when the container's port
 *                    is mapped, e.g. locally: KC_URL=http://127.0.0.1:18080
 *                    KC_INTERNAL_URL=http://127.0.0.1:8080)
 *   KC_ADMIN_USER / KC_ADMIN_PASSWORD  bootstrap admin (default admin/admin)
 */
import { readJwtClaims } from "../packages/auth/src/index.ts";
import { generateKeycloakRealmArtifacts } from "../packages/compiler/src/authoring/generators/keycloak.ts";
import type { AuthorizationConfigFile } from "../packages/compiler/src/authoring/types/authoring.ts";

const KC_URL = (process.env.KC_URL ?? "http://127.0.0.1:8080").replace(/\/$/, "");
const KC_INTERNAL_URL = (process.env.KC_INTERNAL_URL ?? KC_URL).replace(/\/$/, "");
const ADMIN_USER = process.env.KC_ADMIN_USER ?? "admin";
const ADMIN_PASSWORD = process.env.KC_ADMIN_PASSWORD ?? "admin";

const IDP_REALM = "osf-idp";
const BROKER_REALM = "osf-broker";
const OIDC_ALIAS = "customer-workforce";
const SAML_ALIAS = "customer-saml";
const CALLBACK = "http://127.0.0.1/cb";
const GW_SECRET = "gw-dev-secret";
const WORKFORCE_SECRET = "workforce-dev-secret";
const PASSWORD = "Passw0rd!";

// ---------------------------------------------------------------------------
// Tiny test harness
// ---------------------------------------------------------------------------

let step = 0;
function check(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`ASSERTION FAILED: ${message}`);
  console.log(`  ok  ${message}`);
}

/** Like check, but on failure shows what Keycloak actually answered. */
async function checkResponse(condition: unknown, message: string, res: Response): Promise<void> {
  if (condition) {
    console.log(`  ok  ${message}`);
    return;
  }
  const body = await res.text().catch(() => "");
  const text = body.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim();
  throw new Error(`ASSERTION FAILED: ${message}\n  status ${res.status} from ${res.url}\n  ${text.slice(0, 600)}`);
}
function section(title: string) {
  step += 1;
  console.log(`\n[${step}] ${title}`);
}

// ---------------------------------------------------------------------------
// Realms, generated by the compiler's generator (development mode: the local
// stack and CI speak plain http; the production URL/secret rules are covered
// by the generator's unit tests).
// ---------------------------------------------------------------------------

const upstreamConfig: AuthorizationConfigFile = {
  schemaVersion: 2,
  kind: "authorizationConfig",
  realm: { name: IDP_REALM, displayName: "Customer IdP (fixture)", sslRequired: "none", loginWithEmailAllowed: true },
  keycloak: {
    clients: [
      {
        id: OIDC_ALIAS,
        kind: "gateway",
        name: "OSF broker (relying party)",
        devSecret: WORKFORCE_SECRET,
        redirectUris: [`${KC_URL}/realms/${BROKER_REALM}/broker/*`],
        webOrigins: [KC_URL],
      },
    ],
  },
  users: [
    { username: "alice", email: "alice@example.test", firstName: "Alice", lastName: "Upstream", password: PASSWORD, tid: "tenant-alice" },
    { username: "bob", email: "bob@example.test", firstName: "Bob", lastName: "Upstream", password: PASSWORD, tid: "tenant-bob" },
    { username: "carol", email: "carol@example.test", firstName: "Carol", lastName: "Upstream", password: PASSWORD, tid: "tenant-carol" },
  ],
};

const brokerConfig: AuthorizationConfigFile = {
  schemaVersion: 2,
  kind: "authorizationConfig",
  realm: { name: BROKER_REALM, displayName: "OSF broker (under test)", sslRequired: "none", duplicateEmailsAllowed: false },
  keycloak: {
    clients: [
      {
        id: "gw",
        kind: "gateway",
        name: "Product gateway",
        devSecret: GW_SECRET,
        redirectUris: [CALLBACK],
        webOrigins: ["http://127.0.0.1"],
      },
    ],
    identityProviders: [
      {
        alias: OIDC_ALIAS,
        providerId: "oidc",
        displayName: "Continue with company account",
        firstBrokerLoginFlowAlias: "first broker login",
        config: {
          clientId: OIDC_ALIAS,
          issuer: `${KC_URL}/realms/${IDP_REALM}`,
          authorizationUrl: `${KC_URL}/realms/${IDP_REALM}/protocol/openid-connect/auth`,
          tokenUrl: `${KC_INTERNAL_URL}/realms/${IDP_REALM}/protocol/openid-connect/token`,
          jwksUrl: `${KC_INTERNAL_URL}/realms/${IDP_REALM}/protocol/openid-connect/certs`,
          useJwksUrl: true,
          validateSignature: true,
          defaultScope: "openid profile email",
          syncMode: "IMPORT",
        },
        devSecrets: { clientSecret: WORKFORCE_SECRET },
        mappers: [
          {
            name: "tenant",
            identityProviderMapper: "oidc-user-attribute-idp-mapper",
            config: { claim: "tid", "user.attribute": "tid", syncMode: "INHERIT" },
          },
        ],
      },
      {
        alias: SAML_ALIAS,
        providerId: "saml",
        displayName: "Continue with company SAML",
        config: {
          entityId: `${KC_URL}/realms/${BROKER_REALM}`,
          singleSignOnServiceUrl: `${KC_URL}/realms/${IDP_REALM}/protocol/saml`,
          nameIDPolicyFormat: "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
          principalType: "SUBJECT",
          postBindingResponse: true,
          postBindingAuthnRequest: true,
          wantAuthnRequestsSigned: false,
          validateSignature: false,
          syncMode: "IMPORT",
        },
        // A SAML assertion carries only what the IdP asserts; the host maps the
        // profile attributes it needs, exactly as it would for a real customer IdP.
        mappers: [
          {
            name: "tenant",
            identityProviderMapper: "saml-user-attribute-idp-mapper",
            config: { "attribute.name": "tid", "user.attribute": "tid", syncMode: "INHERIT" },
          },
          ...["email", "firstName", "lastName"].map((attr) => ({
            name: attr,
            identityProviderMapper: "saml-user-attribute-idp-mapper",
            config: { "attribute.name": attr, "user.attribute": attr, syncMode: "INHERIT" },
          })),
        ],
      },
    ],
  },
  users: [
    // Shares bob's e-mail. The proof is that logging in as upstream bob does
    // NOT silently become this account.
    { username: "bob-local", email: "bob@example.test", firstName: "Bob", lastName: "Local", password: PASSWORD },
  ],
};

function generate(config: AuthorizationConfigFile): Record<string, unknown> {
  const [artifact] = generateKeycloakRealmArtifacts([], config, "development");
  if (!artifact) throw new Error(`generator emitted nothing for ${config.realm?.name}`);
  return JSON.parse(artifact.contents) as Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Admin API
// ---------------------------------------------------------------------------

async function adminToken(): Promise<string> {
  const res = await fetch(`${KC_URL}/realms/master/protocol/openid-connect/token`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ grant_type: "password", client_id: "admin-cli", username: ADMIN_USER, password: ADMIN_PASSWORD }),
  });
  if (!res.ok) throw new Error(`admin token: ${res.status} ${await res.text()}`);
  return ((await res.json()) as { access_token: string }).access_token;
}

async function admin(token: string, method: string, path: string, body?: unknown): Promise<Response> {
  const res = await fetch(`${KC_URL}/admin${path}`, {
    method,
    headers: { authorization: `Bearer ${token}`, ...(body !== undefined ? { "content-type": "application/json" } : {}) },
    body: body !== undefined ? JSON.stringify(body) : undefined,
  });
  return res;
}

async function adminJson<T>(token: string, path: string): Promise<T> {
  const res = await admin(token, "GET", path);
  if (!res.ok) throw new Error(`GET ${path}: ${res.status} ${await res.text()}`);
  return (await res.json()) as T;
}

async function importRealm(token: string, realm: Record<string, unknown>): Promise<void> {
  const name = realm.realm as string;
  // Idempotent for local re-runs; a fresh CI container has nothing to delete.
  await admin(token, "DELETE", `/realms/${name}`);
  const res = await admin(token, "POST", "/realms", realm);
  if (res.status !== 201) throw new Error(`import ${name}: ${res.status} ${await res.text()}`);
}

// ---------------------------------------------------------------------------
// A browser-less browser: cookie jar + redirect following + form parsing.
// ---------------------------------------------------------------------------

class Session {
  private cookies = new Map<string, { value: string; path: string }>();

  private store(res: Response) {
    const headers = (res.headers as unknown as { getSetCookie?: () => string[] }).getSetCookie?.() ?? [];
    for (const line of headers) {
      const [pair, ...attrs] = line.split(";");
      const eq = pair!.indexOf("=");
      const name = pair!.slice(0, eq).trim();
      const value = pair!.slice(eq + 1).trim();
      const pathAttr = attrs.map((a) => a.trim()).find((a) => a.toLowerCase().startsWith("path="));
      const path = pathAttr ? pathAttr.slice(5) : "/";
      const key = `${name}@${path}`;
      if (value === "" || /max-age=0/i.test(line)) this.cookies.delete(key);
      else this.cookies.set(key, { value, path });
    }
  }

  private header(url: string): string {
    const path = new URL(url).pathname;
    return [...this.cookies.entries()]
      .filter(([, c]) => path.startsWith(c.path))
      .map(([key, c]) => `${key.slice(0, key.indexOf("@"))}=${c.value}`)
      .join("; ");
  }

  /** One request; never follows redirects itself. */
  async request(url: string, init: { method?: string; body?: URLSearchParams } = {}): Promise<Response> {
    const res = await fetch(url, {
      method: init.method ?? "GET",
      redirect: "manual",
      headers: {
        cookie: this.header(url),
        ...(init.body ? { "content-type": "application/x-www-form-urlencoded" } : {}),
      },
      body: init.body,
    });
    this.store(res);
    return res;
  }

  /**
   * Follow redirects until a non-redirect response, or until the Location
   * lands on the product callback — which a browser would leave Keycloak for.
   */
  async follow(res: Response, stopAt = CALLBACK, max = 15): Promise<{ res: Response; url: string }> {
    let current = res;
    let url = current.url;
    for (let i = 0; i < max; i++) {
      if (current.status < 300 || current.status >= 400) return { res: current, url };
      const location = current.headers.get("location");
      if (!location) throw new Error(`redirect without Location from ${url}`);
      url = new URL(location, url).toString();
      if (url.startsWith(stopAt)) return { res: current, url };
      current = await this.request(url);
    }
    throw new Error("too many redirects");
  }
}

function unescapeHtml(s: string): string {
  return s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">");
}

/** The action + hidden inputs of the first <form> whose tag matches `test`. */
function parseForm(html: string, test: (tag: string) => boolean): { action: string; fields: URLSearchParams } {
  const forms = [...html.matchAll(/<form\b[^>]*>[\s\S]*?<\/form>/gi)].map((m) => m[0]);
  const form = forms.find((f) => test(f.slice(0, f.indexOf(">") + 1)));
  if (!form) throw new Error(`no matching <form> in page:\n${html.slice(0, 2000)}`);
  const action = /action="([^"]*)"/i.exec(form)?.[1];
  if (!action) throw new Error("form without action");
  const fields = new URLSearchParams();
  for (const input of form.matchAll(/<input\b[^>]*>/gi)) {
    const tag = input[0];
    if (!/type="hidden"/i.test(tag)) continue;
    const name = /name="([^"]*)"/i.exec(tag)?.[1];
    const value = /value="([^"]*)"/i.exec(tag)?.[1] ?? "";
    if (name) fields.set(name, unescapeHtml(value));
  }
  return { action: unescapeHtml(action), fields };
}

// ---------------------------------------------------------------------------
// Login flows
// ---------------------------------------------------------------------------

/**
 * Start a gateway login on the broker realm, hinting the given provider, and
 * return the upstream login page's HTML. An OIDC provider is reached by
 * redirect; a SAML provider with the POST binding gets an auto-submit form
 * (SAMLRequest) from the broker first, which a browser would submit itself.
 */
async function startBrokeredLogin(session: Session, alias: string): Promise<string> {
  const url =
    `${KC_URL}/realms/${BROKER_REALM}/protocol/openid-connect/auth?` +
    new URLSearchParams({ client_id: "gw", redirect_uri: CALLBACK, response_type: "code", scope: "openid", kc_idp_hint: alias });
  let { res, url: at } = await session.follow(await session.request(url));
  let html = await res.text();
  if (res.status === 200 && at.includes(`/realms/${BROKER_REALM}/`) && /name="SAMLRequest"/.test(html)) {
    const { action, fields } = parseForm(html, () => true);
    check(action.startsWith(`${KC_URL}/realms/${IDP_REALM}/protocol/saml`), "broker issued a SAMLRequest to the authored singleSignOnServiceUrl");
    ({ res, url: at } = await session.follow(await session.request(action, { method: "POST", body: fields })));
    html = await res.text();
  }
  check(res.status === 200 && at.includes(`/realms/${IDP_REALM}/`), `broker handed off to the upstream login page (${alias})`);
  return html;
}

/** Submit the upstream realm's login form. Returns the response after redirects. */
async function submitUpstreamLogin(session: Session, loginHtml: string, username: string) {
  const { action } = parseForm(loginHtml, (tag) => /id="kc-form-login"/.test(tag));
  const posted = await session.request(action, { method: "POST", body: new URLSearchParams({ username, password: PASSWORD, credentialId: "" }) });
  return session.follow(posted);
}

/** Complete a SAML POST binding: the upstream answers with an auto-submit form. */
async function postSamlResponse(session: Session, res: Response) {
  const html = await res.text();
  const { action, fields } = parseForm(html, () => true);
  check(fields.has("SAMLResponse"), "upstream returned a SAMLResponse auto-submit form");
  check(action.startsWith(`${KC_URL}/realms/${BROKER_REALM}/broker/${SAML_ALIAS}/endpoint`), "SAMLResponse is addressed to the broker endpoint");
  const posted = await session.request(action, { method: "POST", body: fields });
  return session.follow(posted);
}

async function exchangeCode(callbackUrl: string): Promise<Record<string, unknown>> {
  const code = new URL(callbackUrl).searchParams.get("code");
  check(!!code, "callback carries an authorization code");
  const res = await fetch(`${KC_URL}/realms/${BROKER_REALM}/protocol/openid-connect/token`, {
    method: "POST",
    headers: { "content-type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({ grant_type: "authorization_code", client_id: "gw", client_secret: GW_SECRET, code: code!, redirect_uri: CALLBACK }),
  });
  if (!res.ok) throw new Error(`token exchange: ${res.status} ${await res.text()}`);
  const { access_token } = (await res.json()) as { access_token: string };
  const claims = readJwtClaims(access_token);
  if (!claims) throw new Error("token exchange returned an access_token that is not a decodable JWT");
  return claims;
}

interface FederatedIdentity { identityProvider: string; userId: string; userName: string }
interface KcUser { id: string; username: string; email?: string; attributes?: Record<string, string[]> }

async function brokerUserByEmail(token: string, email: string): Promise<KcUser[]> {
  return adminJson<KcUser[]>(token, `/realms/${BROKER_REALM}/users?email=${encodeURIComponent(email)}&exact=true&briefRepresentation=false`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log(`Keycloak: ${KC_URL} (internal ${KC_INTERNAL_URL})`);

  section("Generate both realms with the compiler and import them unchanged");
  const upstream = generate(upstreamConfig);
  const broker = generate(brokerConfig);
  check(!("identityProviders" in upstream), "upstream fixture realm authors no identity provider");
  const authoredIdps = broker.identityProviders as Record<string, unknown>[];
  check(authoredIdps.length === 2, "broker realm carries the two authored providers");

  const token = await adminToken();
  await importRealm(token, upstream);
  await importRealm(token, broker);
  check(true, "both generated realms imported through the admin API (201)");

  // Upstream SAML client — a fixture, not under test (see header).
  const samlClient = await admin(token, "POST", `/realms/${IDP_REALM}/clients`, {
    clientId: `${KC_URL}/realms/${BROKER_REALM}`,
    protocol: "saml",
    enabled: true,
    redirectUris: [`${KC_URL}/realms/${BROKER_REALM}/broker/${SAML_ALIAS}/endpoint*`],
    attributes: {
      "saml.client.signature": "false",
      "saml.assertion.signature": "true",
      "saml.server.signature": "true",
      "saml.authnstatement": "true",
      "saml_force_name_id_format": "true",
      "saml_name_id_format": "email",
      "saml.force.post.binding": "true",
    },
    protocolMappers: [
      {
        name: "tid",
        protocol: "saml",
        protocolMapper: "saml-user-attribute-mapper",
        config: { "user.attribute": "tid", "attribute.name": "tid", "attribute.nameformat": "Basic" },
      },
      ...["email", "firstName", "lastName"].map((attr) => ({
        name: attr,
        protocol: "saml",
        protocolMapper: "saml-user-property-mapper",
        config: { "user.attribute": attr, "attribute.name": attr, "attribute.nameformat": "Basic" },
      })),
    ],
  });
  check(samlClient.status === 201, `upstream SAML client created (${samlClient.status})`);

  section("Admin API reads the providers back exactly as authored");
  const instances = await adminJson<Record<string, unknown>[]>(token, `/realms/${BROKER_REALM}/identity-provider/instances`);
  for (const authored of authoredIdps) {
    const live = instances.find((i) => i.alias === authored.alias);
    check(!!live, `provider "${authored.alias}" exists in the imported realm`);
    for (const key of ["providerId", "displayName", "enabled", "trustEmail", "storeToken", "linkOnly", "hideOnLogin"]) {
      check(JSON.stringify(live![key]) === JSON.stringify(authored[key]), `  ${authored.alias}.${key} = ${JSON.stringify(authored[key])}`);
    }
    const liveConfig = live!.config as Record<string, string>;
    for (const [k, v] of Object.entries(authored.config as Record<string, string>)) {
      if (k === "clientSecret") {
        // Keycloak never reads a secret back; it masks it. Not a transformation
        // of the authored value — the login below is what proves the secret.
        check(liveConfig[k] === "**********", `  ${authored.alias}.config.${k} is masked on read`);
        continue;
      }
      check(liveConfig[k] === v, `  ${authored.alias}.config.${k} survived byte-for-byte`);
    }
  }
  const mappers = await adminJson<Record<string, unknown>[]>(token, `/realms/${BROKER_REALM}/identity-provider/instances/${OIDC_ALIAS}/mappers`);
  check(mappers.some((m) => m.name === "tenant" && m.identityProviderMapper === "oidc-user-attribute-idp-mapper"), "OIDC mapper bound to its provider");

  section("Dedicated OIDC provider: first login for alice, with the attribute mapper");
  let session = new Session();
  let loginPage = await startBrokeredLogin(session, OIDC_ALIAS);
  let outcome = await submitUpstreamLogin(session, loginPage, "alice");
  await checkResponse(outcome.url.startsWith(CALLBACK), `brokered login ended at the product callback (${outcome.url.split("?")[0]})`, outcome.res);
  const first = await exchangeCode(outcome.url);
  check(first.preferred_username === "alice", `broker token is for alice (preferred_username=${first.preferred_username})`);
  check(first.tid === "tenant-alice", `mapper carried the upstream tid claim onto the brokered user (tid=${first.tid})`);
  const [aliceBroker] = await brokerUserByEmail(token, "alice@example.test");
  check(!!aliceBroker, "alice now exists in the broker realm");
  let fed = await adminJson<FederatedIdentity[]>(token, `/realms/${BROKER_REALM}/users/${aliceBroker!.id}/federated-identity`);
  check(fed.some((f) => f.identityProvider === OIDC_ALIAS), `alice is federated through "${OIDC_ALIAS}"`);
  // The attribute itself is not asserted through the admin API: a realm with
  // the default user-profile policy does not expose unmanaged attributes there.
  // The `tid` claim in the broker's own token above is the stronger proof.

  section("Repeat login for alice is a plain login and keeps the same subject");
  session = new Session();
  loginPage = await startBrokeredLogin(session, OIDC_ALIAS);
  outcome = await submitUpstreamLogin(session, loginPage, "alice");
  await checkResponse(outcome.url.startsWith(CALLBACK), "repeat login went straight to the callback", outcome.res);
  const second = await exchangeCode(outcome.url);
  check(second.sub === first.sub, "same broker subject on repeat login");
  check((await brokerUserByEmail(token, "alice@example.test")).length === 1, "still exactly one alice in the broker realm");

  section("An e-mail match with an existing local account is NOT linked silently");
  session = new Session();
  loginPage = await startBrokeredLogin(session, OIDC_ALIAS);
  outcome = await submitUpstreamLogin(session, loginPage, "bob");
  check(!outcome.url.startsWith(CALLBACK), "flow did not reach the callback");
  check(outcome.res.status === 200, `broker answered with a page, not a code (${outcome.res.status})`);
  const confirmPage = await outcome.res.text();
  check(/linkAccount|kc-idp-confirm-link|already exists/i.test(confirmPage), "…and that page is Keycloak's confirm-link step");
  const bobs = await brokerUserByEmail(token, "bob@example.test");
  check(bobs.length === 1 && bobs[0]!.username === "bob-local", "only the pre-existing local account carries bob's e-mail");
  fed = await adminJson<FederatedIdentity[]>(token, `/realms/${BROKER_REALM}/users/${bobs[0]!.id}/federated-identity`);
  check(fed.length === 0, "the local account has no federated identity");

  section("Generic SAML provider: first login for carol, with the attribute mapper");
  session = new Session();
  loginPage = await startBrokeredLogin(session, SAML_ALIAS);
  const afterLogin = await submitUpstreamLogin(session, loginPage, "carol");
  await checkResponse(afterLogin.res.status === 200, "upstream SAML IdP responded with the POST-binding page", afterLogin.res);
  outcome = await postSamlResponse(session, afterLogin.res);
  await checkResponse(outcome.url.startsWith(CALLBACK), "SAML-brokered login ended at the product callback", outcome.res);
  const saml = await exchangeCode(outcome.url);
  check(saml.tid === "tenant-carol", `SAML mapper carried the upstream tid attribute (tid=${saml.tid})`);
  const [carol] = await brokerUserByEmail(token, "carol@example.test");
  check(!!carol, "carol now exists in the broker realm");
  fed = await adminJson<FederatedIdentity[]>(token, `/realms/${BROKER_REALM}/users/${carol!.id}/federated-identity`);
  check(fed.some((f) => f.identityProvider === SAML_ALIAS), `carol is federated through "${SAML_ALIAS}"`);

  console.log("\nBroker acceptance passed.");
}

main().catch((err) => {
  console.error(`\n${err instanceof Error ? err.stack ?? err.message : String(err)}`);
  process.exit(1);
});
