// SPDX-License-Identifier: BUSL-1.1
/**
 * Scaffolds a versioned bespoke migration:
 *
 *   bun run db:migration:new <kebab-name>       (cwd apps/api, or repo root)
 *
 * Computes the next version number from the files in ./versioned/ (0001 is
 * the generated platform-schema baseline, so the first bespoke migration is
 * 0002), writes a template migration file, and registers it in
 * ./versioned/index.ts via the marker comments there (falling back to
 * printed instructions if the markers are missing).
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { join } from "node:path";

const namePattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const importsMarker = "// migration-registry:imports";
const entriesMarker = "// migration-registry:entries";

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

const name = process.argv[2];
if (name === undefined || name.length === 0) {
  fail(
    "Usage: bun run db:migration:new <kebab-name>\n" +
      'Example: bun run db:migration:new split-relation-address',
  );
}
if (!namePattern.test(name)) {
  fail(
    `Invalid migration name "${name}" — use kebab-case: lowercase letters, digits, and single hyphens (e.g. "split-relation-address").`,
  );
}

const versionedDir = fileURLToPath(new URL("./versioned/", import.meta.url));
const registryPath = join(versionedDir, "index.ts");

const existingFiles = await readdir(versionedDir);
const existingNumbers = existingFiles
  .map((file) => /^(\d{4})_.+\.ts$/.exec(file)?.[1])
  .filter((num): num is string => num !== undefined)
  .map(Number);

// 0001 is the generated baseline; bespoke migrations start at 0002.
const nextNumber = Math.max(1, ...existingNumbers) + 1;
const numberText = String(nextNumber).padStart(4, "0");
const version = `${numberText}_${name}`;
const fileName = `${version}.ts`;
const filePath = join(versionedDir, fileName);

if (existingFiles.includes(fileName)) {
  fail(`Migration file already exists: ${filePath}`);
}

const template = [
  `import { sql, type Kysely } from "kysely";`,
  `import type { VersionedMigration } from "../versioned-runner.js";`,
  ``,
  `/**`,
  ` * ${version}`,
  ` *`,
  ` * Bespoke schema transformation. up() runs in a transaction on the`,
  ` * migration connection, after the platform baseline and BEFORE the`,
  ` * generated roll-forward — use it to transform the live schema (rename,`,
  ` * retype, backfill, drop) so the generated manifest diff becomes additive,`,
  ` * then rerun \`bun run db:migrate\`. If you create permanent tables here,`,
  ` * prefer adding them to the authoring YAML so the manifest owns them.`,
  ` *`,
  ` * Applied migrations are immutable: the sha256 of THIS FILE is recorded in`,
  ` * platform.schema_migrations and re-verified on every migrate run. Once`,
  ` * this migration has been applied anywhere, do not edit this file —`,
  ` * scaffold a new migration instead (bun run db:migration:new <name>).`,
  ` */`,
  `const migration: VersionedMigration = {`,
  `  version: "${version}",`,
  `  fileUrl: import.meta.url,`,
  `  async up(db: Kysely<any>): Promise<void> {`,
  `    // Replace this throw with the schema transformation, e.g.:`,
  `    //   await sql\`alter table "erp"."relations" rename column "notes" to "remarks"\`.execute(db);`,
  `    throw new Error(`,
  `      "Versioned migration ${version} is not implemented yet — write up() and remove this throw.",`,
  `    );`,
  `  },`,
  `};`,
  ``,
  `export default migration;`,
  ``,
].join("\n");

await writeFile(filePath, template, { flag: "wx" });

const importName = `m${numberText}${name
  .split("-")
  .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
  .join("")}`;
const importLine = `import ${importName} from "./${version}.js";`;
const entryLine = `  ${importName},`;

const registrySource = await readFile(registryPath, "utf8");
const registryLines = registrySource.split("\n");
const importsIndex = registryLines.findIndex((line) =>
  line.trimStart().startsWith(importsMarker),
);
const entriesIndex = registryLines.findIndex((line) =>
  line.trimStart().startsWith(entriesMarker),
);

let registered = false;
if (importsIndex !== -1 && entriesIndex > importsIndex) {
  registryLines.splice(entriesIndex, 0, entryLine);
  registryLines.splice(importsIndex + 1, 0, importLine);
  await writeFile(registryPath, registryLines.join("\n"));
  registered = true;
}

console.log(`Created ${filePath}`);
if (registered) {
  console.log(`Registered ${version} in ${registryPath}`);
} else {
  console.log(
    `Could not find the registry markers in ${registryPath} — register it manually:\n` +
      `  ${importLine}\n` +
      `  ...and append to versionedMigrations:\n` +
      `  ${entryLine}`,
  );
}
console.log(
  [
    "",
    "Next steps:",
    `  1. Implement up() in ${fileName} (and remove the placeholder throw).`,
    "  2. Run: bun run db:migrate",
    "  3. Never edit this file after it has been applied anywhere — its sha256 is recorded and verified.",
  ].join("\n"),
);
